import type { ExerciseSeed } from './types';

/** Every exercise's artwork lives at `exercises/<id>`. */
function ex(seed: Omit<ExerciseSeed, 'visualAsset'>): ExerciseSeed {
  return { ...seed, visualAsset: `exercises/${seed.id}` };
}

/**
 * Exercise library. Ids are permanent: workouts, sessions and swaps reference them.
 * Rep convention: for alternating or two-sided movements, each side counts as one rep
 * unless the instructions say otherwise.
 */
export const EXERCISE_SEEDS: ExerciseSeed[] = [
  // ---------------------------------------------------------------------------
  // Push
  // ---------------------------------------------------------------------------
  ex({
    id: 'wall-push-up',
    name: 'Wall Push-up',
    description: 'Incline push-up against a wall; the first rung of the push-up ladder.',
    instructions: "Stand an arm's length from a wall, hands at chest height and slightly wider than your shoulders. Keep one straight line from head to heels as you bend and press.",
    startPosition: 'Standing facing a wall, palms flat at chest height, heels down.',
    movementSequence: 'Bend the elbows to bring your chest toward the wall, then press back to straight arms.',
    cues: ['Brace your core', 'Elbows at about 45°', 'Move as one plank'],
    mistakes: ['Sagging hips', 'Only the head travels toward the wall'],
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    category: 'push',
    equipment: ['bodyweight'],
    impactLevel: 'low',
    harderVariantId: 'knee-push-up',
  }),
  ex({
    id: 'knee-push-up',
    name: 'Knee Push-up',
    description: 'Full-range push-up from the knees.',
    instructions: 'Hands under your shoulders, knees on the floor behind you. Keep a straight line from knees to head and lower your chest between your hands.',
    startPosition: 'High plank on hands and knees, hips extended.',
    movementSequence: 'Lower your chest to just above the floor, then press back to straight arms.',
    cues: ['Straight line from knee to head', 'Elbows at about 45°', 'Chest leads, not the chin'],
    mistakes: ['Hips piking up', 'Cutting the bottom range short'],
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    category: 'push',
    equipment: ['mat'],
    impactLevel: 'low',
    easierVariantId: 'wall-push-up',
    harderVariantId: 'push-up',
  }),
  ex({
    id: 'push-up',
    name: 'Push-up',
    description: 'Standard floor push-up: chest to the floor, full lockout.',
    instructions: 'Hands just wider than your shoulders, body in a rigid plank. Lower until your chest nearly touches the floor, then press to full lockout.',
    startPosition: 'High plank, hands under shoulders, feet together.',
    movementSequence: 'Lower your chest to the floor as one unit, press back to straight arms.',
    cues: ['Ribs down', 'Glutes tight', 'Elbows at about 45°'],
    mistakes: ['Partial range', 'Hips sagging', 'Elbows flared to 90°'],
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders', 'abs'],
    category: 'push',
    equipment: ['bodyweight'],
    impactLevel: 'medium',
    easierVariantId: 'knee-push-up',
    harderVariantId: 'decline-push-up',
  }),
  ex({
    id: 'decline-push-up',
    name: 'Decline Push-up',
    description: 'Feet-elevated push-up that shifts load to the upper chest and shoulders.',
    instructions: 'Feet on a bench or sturdy step, hands on the floor under your shoulders. Keep the plank rigid and lower under control.',
    startPosition: 'Plank with feet on a bench, hands under shoulders.',
    movementSequence: 'Lower your chest toward the floor, then press back to straight arms.',
    cues: ['Control the descent', 'Squeeze glutes so the hips stay level'],
    mistakes: ['Bouncing at the bottom', 'Hips piking toward the ceiling'],
    primaryMuscles: ['chest', 'shoulders'],
    secondaryMuscles: ['triceps', 'abs'],
    category: 'push',
    equipment: ['bench'],
    impactLevel: 'medium',
    easierVariantId: 'push-up',
  }),
  ex({
    id: 'pike-push-up',
    name: 'Pike Push-up',
    description: 'Vertical push from a pike that builds the shoulders.',
    instructions: 'Walk your feet in until your hips are high. Bend the elbows to lower the top of your head toward the floor just in front of your hands, then press back.',
    startPosition: 'Inverted V, hands shoulder-width, hips high.',
    movementSequence: 'Bend the elbows so the head travels down and slightly forward, then press back to straight arms.',
    cues: ['Look between your hands', 'Keep the hips stacked high', 'Elbows track back, not out'],
    mistakes: ['Elbows flaring wide', 'Hips dropping into a regular push-up'],
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps', 'upper_back'],
    category: 'push',
    equipment: ['bodyweight'],
    impactLevel: 'medium',
  }),
  ex({
    id: 'diamond-push-up',
    name: 'Diamond Push-up',
    description: 'Narrow-hand push-up that biases the triceps.',
    instructions: 'Touch thumbs and index fingers to form a diamond under your chest. Lower your chest to your hands with the elbows tracking back.',
    startPosition: 'High plank with hands together under the sternum.',
    movementSequence: 'Lower your chest to the backs of your hands, press to lockout.',
    cues: ['Elbows brush your ribs', 'Body stays in one line'],
    mistakes: ['Hands too far forward', 'Shoulders shrugging toward the ears'],
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['chest', 'shoulders'],
    category: 'push',
    equipment: ['bodyweight'],
    impactLevel: 'medium',
    easierVariantId: 'push-up',
  }),
  ex({
    id: 'tricep-dip',
    name: 'Tricep Dip',
    description: 'Bench dip for the triceps.',
    instructions: 'Hands on the edge of a stable bench or chair behind you. Lower until your elbows reach about 90°, then press back up.',
    startPosition: 'Seated on the bench edge, hands beside your hips, then slide your hips forward off the bench.',
    movementSequence: 'Lower the hips by bending the elbows, press back to straight arms.',
    cues: ['Shoulders down, away from the ears', 'Elbows point straight back', 'Hips close to the bench'],
    mistakes: ['Shrugging the shoulders', 'Dropping past a comfortable shoulder range'],
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['chest', 'shoulders'],
    category: 'push',
    equipment: ['bench'],
    impactLevel: 'medium',
  }),
  ex({
    id: 'archer-push-up',
    name: 'Archer Push-up',
    description: 'Wide push-up that shifts the load onto one arm at a time.',
    instructions: 'Set your hands very wide. Lower toward one hand while the other arm stays nearly straight, press up, then alternate sides.',
    startPosition: 'High plank, hands about twice shoulder-width, fingers turned slightly out.',
    movementSequence: 'Lower toward one hand, press back up, repeat toward the other hand.',
    cues: ['Body stays square to the floor', 'The straight arm slides, it does not lock'],
    mistakes: ['Hips twisting', 'Cutting the depth short'],
    primaryMuscles: ['chest', 'triceps'],
    secondaryMuscles: ['shoulders', 'abs'],
    category: 'push',
    equipment: ['bodyweight'],
    impactLevel: 'medium',
    easierVariantId: 'push-up',
  }),
  ex({
    id: 'hindu-push-up',
    name: 'Hindu Push-up',
    description: 'Flowing push-up that dives from a pike into a cobra.',
    instructions: 'From a high pike, bend the elbows and swoop your chest low along the floor, then press up into a cobra. Push the hips back to the pike to finish the rep.',
    startPosition: 'Inverted V with hips high, hands and feet shoulder-width.',
    movementSequence: 'Dive the chest forward and low, arc up into a cobra, press back to the pike.',
    cues: ['Skim the chest low', 'One smooth, continuous arc'],
    mistakes: ['Dropping the hips too early', 'Crunching the low back in the cobra'],
    primaryMuscles: ['shoulders', 'chest', 'triceps'],
    secondaryMuscles: ['upper_back', 'lower_back'],
    category: 'push',
    equipment: ['bodyweight'],
    impactLevel: 'medium',
  }),
  ex({
    id: 'dumbbell-press',
    name: 'Dumbbell Overhead Press',
    description: 'Standing strict press with two dumbbells.',
    instructions: 'Hold the dumbbells at your shoulders, brace, and press straight overhead to lockout without leaning back.',
    startPosition: 'Standing, feet hip-width, dumbbells at shoulder height.',
    movementSequence: 'Press to lockout, lower back to the shoulders under control.',
    cues: ['Squeeze glutes, ribs down', 'Biceps by the ears at lockout'],
    mistakes: ['Arching the low back', 'Pressing forward instead of up'],
    primaryMuscles: ['shoulders', 'triceps'],
    secondaryMuscles: ['upper_back', 'abs'],
    category: 'push',
    equipment: ['dumbbells'],
    impactLevel: 'low',
  }),
  ex({
    id: 'dumbbell-floor-press',
    name: 'Dumbbell Floor Press',
    description: 'Chest press lying on the floor; the floor sets a shoulder-friendly range.',
    instructions: 'Lie on your back with knees bent and press two dumbbells from your chest to straight arms. Lower until your upper arms touch the floor.',
    startPosition: 'Lying on your back, knees bent, dumbbells at chest level.',
    movementSequence: 'Press up, lower until the upper arms rest on the floor, press again.',
    cues: ['Elbows at about 45°', 'Pause softly on the floor'],
    mistakes: ['Bouncing the elbows off the floor', 'Flaring the elbows wide'],
    primaryMuscles: ['chest', 'triceps'],
    secondaryMuscles: ['shoulders'],
    category: 'push',
    equipment: ['dumbbells'],
    impactLevel: 'low',
  }),

  // ---------------------------------------------------------------------------
  // Pull
  // ---------------------------------------------------------------------------
  ex({
    id: 'dead-hang',
    name: 'Dead Hang',
    description: 'Hang from the bar to build grip and shoulder control.',
    instructions: 'Grip the bar overhand and hang with straight arms and feet off the floor. Keep the shoulders gently engaged and breathe.',
    startPosition: 'Hanging from the bar, arms straight, feet off the floor.',
    movementSequence: 'Hold the hang for the full time; if your grip fails, step down and get straight back up.',
    cues: ['Shoulders away from the ears', 'Squeeze the bar hard', 'Ribs down'],
    mistakes: ['Shrugging into the ears', 'Swinging'],
    primaryMuscles: ['forearms', 'lats'],
    secondaryMuscles: ['shoulders', 'upper_back'],
    category: 'pull',
    equipment: ['pull-up-bar'],
    impactLevel: 'low',
    harderVariantId: 'negative-pull-up',
  }),
  ex({
    id: 'negative-pull-up',
    name: 'Negative Pull-up',
    description: 'Slow lowering from the top of a pull-up; builds the strength for the full rep.',
    instructions: 'Jump or step up so your chin is over the bar, then lower yourself as slowly as you can, aiming for 3-5 seconds, to a dead hang.',
    startPosition: 'Chin over the bar, elbows bent, using a jump or a step to get there.',
    movementSequence: 'Lower slowly to straight arms, step back up, repeat.',
    cues: ['Fight the whole way down', 'Count 3-5 seconds per rep', 'Shoulders packed, not shrugged'],
    mistakes: ['Dropping through the bottom half', 'Jumping up so hard you swing'],
    primaryMuscles: ['lats', 'biceps'],
    secondaryMuscles: ['upper_back', 'forearms'],
    category: 'pull',
    equipment: ['pull-up-bar'],
    impactLevel: 'medium',
    easierVariantId: 'dead-hang',
    harderVariantId: 'pull-up',
  }),
  ex({
    id: 'chin-up',
    name: 'Chin-up',
    description: 'Underhand-grip pull-up with extra help from the biceps.',
    instructions: 'Hang with palms facing you, hands shoulder-width. Pull until your chin clears the bar, then lower to straight arms.',
    startPosition: 'Dead hang, palms facing you.',
    movementSequence: 'Pull the elbows down to the ribs, chin over the bar, lower under control.',
    cues: ['Pull your chest to the bar', 'Full lockout at the bottom'],
    mistakes: ['Craning the neck to clear the bar', 'Dropping fast on the way down'],
    primaryMuscles: ['lats', 'biceps'],
    secondaryMuscles: ['upper_back', 'forearms'],
    category: 'pull',
    equipment: ['pull-up-bar'],
    impactLevel: 'medium',
    easierVariantId: 'negative-pull-up',
    harderVariantId: 'pull-up',
  }),
  ex({
    id: 'pull-up',
    name: 'Pull-up',
    description: 'Strict overhand pull from a dead hang to chin over the bar.',
    instructions: 'Hang with an overhand grip just wider than your shoulders. Pull until your chin clears the bar, then lower to straight arms under control.',
    startPosition: 'Dead hang, palms facing away, arms straight.',
    movementSequence: 'Pull the shoulders down and back, drive the elbows to the ribs, chin over the bar, lower fully.',
    cues: ['Start every rep from straight arms', 'Drive the elbows down', 'Legs together, ribs down'],
    mistakes: ['Half reps that stop short of straight arms', 'Kicking or swinging for momentum'],
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'upper_back', 'forearms'],
    category: 'pull',
    equipment: ['pull-up-bar'],
    impactLevel: 'medium',
    easierVariantId: 'negative-pull-up',
  }),
  ex({
    id: 'dumbbell-row',
    name: 'Dumbbell Row',
    description: 'Bent-over row with two dumbbells.',
    instructions: 'Hinge forward with a flat back, arms hanging, and row both dumbbells to your lower ribs. Lower with control.',
    startPosition: 'Hinged to about 45°, knees soft, dumbbells hanging under the shoulders.',
    movementSequence: 'Row the elbows back past the ribs, squeeze, lower.',
    cues: ['Flat back', 'Elbows close to the body', 'Squeeze the shoulder blades'],
    mistakes: ['Standing up as you row', 'Jerking the weight'],
    primaryMuscles: ['lats', 'upper_back'],
    secondaryMuscles: ['biceps', 'forearms', 'lower_back'],
    category: 'pull',
    equipment: ['dumbbells'],
    impactLevel: 'low',
    harderVariantId: 'renegade-row',
  }),
  ex({
    id: 'renegade-row',
    name: 'Renegade Row',
    description: 'Alternating dumbbell row from a high plank.',
    instructions: 'In a high plank with your hands on two dumbbells, row one dumbbell to your ribs without rotating the hips, lower it, then switch.',
    startPosition: 'High plank on two hex or flat-sided dumbbells, feet wide.',
    movementSequence: 'Row, lower, switch sides.',
    cues: ['Feet wide', 'Hips square to the floor', 'Push the planted hand into the floor'],
    mistakes: ['Hips twisting open', 'Using round dumbbells that roll'],
    primaryMuscles: ['lats', 'upper_back', 'abs'],
    secondaryMuscles: ['obliques', 'biceps', 'shoulders'],
    category: 'pull',
    equipment: ['dumbbells'],
    impactLevel: 'medium',
    easierVariantId: 'dumbbell-row',
  }),
  ex({
    id: 'band-pull-apart',
    name: 'Band Pull-apart',
    description: 'Pull a resistance band apart at chest height for the upper back.',
    instructions: 'Hold a band at shoulder width with straight arms in front of your chest. Pull it apart until it touches your chest, then return slowly.',
    startPosition: 'Standing, arms straight in front at chest height, band lightly taut.',
    movementSequence: 'Pull apart, squeeze the shoulder blades, return under control.',
    cues: ['Shoulders down', 'Squeeze the shoulder blades together', 'Control the return'],
    mistakes: ['Shrugging', 'Bending the elbows to cheat the range'],
    primaryMuscles: ['upper_back', 'shoulders'],
    secondaryMuscles: [],
    category: 'pull',
    equipment: ['band'],
    impactLevel: 'low',
  }),

  // ---------------------------------------------------------------------------
  // Squat
  // ---------------------------------------------------------------------------
  ex({
    id: 'air-squat',
    name: 'Air Squat',
    description: 'Bodyweight squat to full depth.',
    instructions: 'Feet shoulder-width, toes slightly out. Sit the hips back and down until your thighs are at least parallel, then stand tall.',
    startPosition: 'Standing tall, feet shoulder-width.',
    movementSequence: 'Squat until the hip crease is level with or below the knees, drive up to full hip extension.',
    cues: ['Knees track over toes', 'Chest up', 'Whole foot on the floor'],
    mistakes: ['Heels lifting', 'Knees caving in', 'Stopping short of parallel'],
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'adductors'],
    category: 'squat',
    equipment: ['bodyweight'],
    impactLevel: 'low',
    harderVariantId: 'jump-squat',
  }),
  ex({
    id: 'jump-squat',
    name: 'Jump Squat',
    description: 'Squat that explodes into a vertical jump.',
    instructions: 'Squat to about parallel, then drive through the floor into a jump. Land softly and sink straight into the next rep.',
    startPosition: 'Standing, feet shoulder-width.',
    movementSequence: 'Squat, explode up, land on the balls of the feet and absorb into the next squat.',
    cues: ['Soft, quiet landing', 'Swing the arms for height', 'Knees out on landing'],
    mistakes: ['Landing stiff-legged', 'Knees caving on landing'],
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['calves', 'hamstrings'],
    category: 'squat',
    equipment: ['bodyweight'],
    impactLevel: 'high',
    easierVariantId: 'air-squat',
    harderVariantId: 'tuck-jump',
  }),
  ex({
    id: 'step-up',
    name: 'Step-up',
    description: 'Single-leg step onto a box or bench.',
    instructions: 'Place your whole foot on a sturdy bench and drive through it to stand tall on top, then step down with control. Alternate legs.',
    startPosition: 'Facing a stable bench or step, about knee height.',
    movementSequence: 'Step up, stand tall, step down, switch legs.',
    cues: ['Knee tracks over the foot', 'Drive through the top heel'],
    mistakes: ['Pushing off the bottom foot', 'Using an unstable surface'],
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'calves'],
    category: 'squat',
    equipment: ['bench'],
    impactLevel: 'medium',
  }),
  ex({
    id: 'squat-hold',
    name: 'Squat Hold',
    description: 'Isometric hold at squat depth.',
    instructions: 'Sit into a squat at or just above parallel and hold, chest up and weight through the whole foot.',
    startPosition: 'Squat depth, arms forward for balance.',
    movementSequence: 'Hold the position for the full time without rising.',
    cues: ['Weight in the heels', 'Knees pushed out'],
    mistakes: ['Creeping up out of depth'],
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes', 'adductors'],
    category: 'squat',
    equipment: ['bodyweight'],
    impactLevel: 'low',
  }),
  ex({
    id: 'wall-sit',
    name: 'Wall Sit',
    description: 'Seated hold with your back against a wall.',
    instructions: 'Slide down the wall until your thighs are parallel to the floor and hold.',
    startPosition: 'Back flat against a wall, feet about two feet out.',
    movementSequence: 'Hold the 90° knee bend for the full time.',
    cues: ['Knees over ankles', 'Back flat on the wall'],
    mistakes: ['Hands pushing on the thighs', 'Sitting too high'],
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes'],
    category: 'squat',
    equipment: ['bodyweight'],
    impactLevel: 'low',
  }),
  ex({
    id: 'cossack-squat',
    name: 'Cossack Squat',
    description: 'Deep side-to-side squat in a wide stance.',
    instructions: 'From a wide stance, sit down over one leg while the other stays straight with the toes up, then shift to the other side.',
    startPosition: 'Wide stance, toes slightly out.',
    movementSequence: 'Squat to one side, shift through the middle, squat to the other side.',
    cues: ['Working heel stays down', 'Chest up'],
    mistakes: ['Collapsing the chest', 'Lifting the working heel'],
    primaryMuscles: ['quads', 'adductors'],
    secondaryMuscles: ['glutes', 'hamstrings'],
    category: 'squat',
    equipment: ['bodyweight'],
    impactLevel: 'medium',
    easierVariantId: 'lateral-lunge',
  }),
  ex({
    id: 'pistol-squat',
    name: 'Pistol Squat',
    description: 'Single-leg squat to full depth with the free leg held forward.',
    instructions: 'Stand on one leg with the other extended in front, squat as low as you can control and stand back up. Split reps evenly between legs; hold a door frame or squat to a bench to scale.',
    startPosition: 'Standing on one leg, arms reaching forward for balance.',
    movementSequence: 'Lower under control with the free leg forward, drive back up.',
    cues: ['Heel stays down', 'Knee tracks over the toes', 'Reach the arms forward'],
    mistakes: ['Collapsing at the bottom', 'Knee caving inward'],
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['adductors', 'hip_flexors', 'abs'],
    category: 'squat',
    equipment: ['bodyweight'],
    impactLevel: 'medium',
    easierVariantId: 'air-squat',
  }),
  ex({
    id: 'goblet-squat',
    name: 'Goblet Squat',
    description: 'Front-loaded squat holding one dumbbell (or a kettlebell) at the chest.',
    instructions: 'Hold one dumbbell vertically against your chest. Squat down between your knees to at least parallel and stand tall. A kettlebell held by the horns works too.',
    startPosition: 'Standing, feet shoulder-width, dumbbell held at the chest.',
    movementSequence: 'Sit down between the knees with the elbows inside them, drive back up.',
    cues: ['Elbows inside the knees', 'Chest proud', 'Whole foot down'],
    mistakes: ['Dumbbell drifting away from the chest', 'Heels lifting'],
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['adductors', 'abs', 'upper_back'],
    category: 'squat',
    equipment: ['dumbbells'],
    impactLevel: 'low',
    easierVariantId: 'air-squat',
  }),
  ex({
    id: 'dumbbell-thruster',
    name: 'Dumbbell Thruster',
    description: 'Front squat that drives straight into an overhead press.',
    instructions: 'Hold two dumbbells at your shoulders, squat to parallel, then drive up and use that momentum to press the dumbbells overhead to lockout.',
    startPosition: 'Standing, dumbbells racked at the shoulders.',
    movementSequence: 'Squat, stand up fast, press overhead, return the dumbbells to the shoulders.',
    cues: ['Drive with the legs, finish with the arms', 'Lock out with the biceps by the ears'],
    mistakes: ['Pressing before the hips finish', 'Elbows dropping in the squat'],
    primaryMuscles: ['quads', 'shoulders'],
    secondaryMuscles: ['glutes', 'triceps', 'abs'],
    category: 'squat',
    equipment: ['dumbbells'],
    impactLevel: 'medium',
    easierVariantId: 'goblet-squat',
  }),

  // ---------------------------------------------------------------------------
  // Lunge
  // ---------------------------------------------------------------------------
  ex({
    id: 'walking-lunge',
    name: 'Walking Lunge',
    description: 'Alternating forward lunges travelling across the floor.',
    instructions: 'Take a long step, lower until the back knee lightly touches the floor, then step through into the next lunge.',
    startPosition: 'Standing tall with space in front of you.',
    movementSequence: 'Step forward, lower, drive through the front foot and bring the back leg through.',
    cues: ['Torso upright', 'Front knee over the foot', 'Long, controlled steps'],
    mistakes: ['Short steps', 'Slamming the back knee'],
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'adductors'],
    category: 'lunge',
    equipment: ['bodyweight'],
    impactLevel: 'medium',
    easierVariantId: 'reverse-lunge',
    harderVariantId: 'jumping-lunge',
  }),
  ex({
    id: 'reverse-lunge',
    name: 'Reverse Lunge',
    description: 'Step-back lunge; knee-friendly and easy to balance.',
    instructions: 'Step one foot back, lower until both knees are near 90°, then drive through the front heel to return. Alternate legs.',
    startPosition: 'Standing, feet hip-width.',
    movementSequence: 'Step back into the lunge, lower, drive up to standing.',
    cues: ['Front shin vertical', 'Weight in the front heel'],
    mistakes: ['Leaning far forward', 'Back knee crashing down'],
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    category: 'lunge',
    equipment: ['bodyweight'],
    impactLevel: 'low',
    harderVariantId: 'walking-lunge',
  }),
  ex({
    id: 'jumping-lunge',
    name: 'Jumping Lunge',
    description: 'Alternating lunges with a jump switch in the air.',
    instructions: 'From a lunge, jump and switch legs mid-air, landing softly in the opposite lunge. Each landing counts as one rep.',
    startPosition: 'Split stance in a lunge, both knees bent.',
    movementSequence: 'Jump, switch legs, land softly and sink into the next lunge.',
    cues: ['Absorb every landing', 'Stay tall through the torso'],
    mistakes: ['Front knee collapsing inward', 'Landing on a straight leg'],
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['calves', 'hamstrings', 'hip_flexors'],
    category: 'lunge',
    equipment: ['bodyweight'],
    impactLevel: 'high',
    easierVariantId: 'walking-lunge',
  }),
  ex({
    id: 'lateral-lunge',
    name: 'Lateral Lunge',
    description: 'Side step into a single-leg squat for the hips and inner thighs.',
    instructions: 'Step wide to one side and sit back into that hip with the other leg straight, then push back to center. Alternate sides.',
    startPosition: 'Standing, feet together.',
    movementSequence: 'Step wide, sit back, push back to center, switch sides.',
    cues: ['Sit back, not down', 'Both feet point forward', 'Chest up'],
    mistakes: ['Knee collapsing inward', 'Rounding the back'],
    primaryMuscles: ['adductors', 'quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    category: 'lunge',
    equipment: ['bodyweight'],
    impactLevel: 'low',
    harderVariantId: 'cossack-squat',
  }),
  ex({
    id: 'curtsy-lunge',
    name: 'Curtsy Lunge',
    description: 'Lunge with the back leg crossing behind; targets the side glutes.',
    instructions: 'Step one foot diagonally behind the other, lower both knees, then drive back up. Alternate sides.',
    startPosition: 'Standing, feet hip-width.',
    movementSequence: 'Cross back into the lunge, lower, return, switch sides.',
    cues: ['Hips square to the front', 'Front knee over the foot'],
    mistakes: ['Twisting the hips', 'Front knee caving'],
    primaryMuscles: ['glutes', 'quads'],
    secondaryMuscles: ['adductors', 'hamstrings'],
    category: 'lunge',
    equipment: ['bodyweight'],
    impactLevel: 'low',
  }),
  ex({
    id: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    description: 'Rear-foot-elevated split squat.',
    instructions: 'Rest the top of your back foot on a bench, lower until the front thigh is near parallel and drive up through the front foot. Do half the reps on one leg, then switch.',
    startPosition: 'Split stance, back foot on a bench, front foot about two feet forward.',
    movementSequence: 'Lower straight down, drive up; finish one leg, then switch.',
    cues: ['Front heel stays down', 'A slight forward lean is fine', 'Lower straight down'],
    mistakes: ['Front foot too close to the bench', 'Front knee caving inward'],
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['adductors', 'hamstrings', 'hip_flexors'],
    category: 'lunge',
    equipment: ['bench'],
    impactLevel: 'medium',
    easierVariantId: 'reverse-lunge',
  }),
  ex({
    id: 'dumbbell-lunge',
    name: 'Dumbbell Reverse Lunge',
    description: 'Alternating reverse lunge holding dumbbells at your sides.',
    instructions: 'Hold a dumbbell in each hand, step back into a lunge until the back knee nearly touches, and drive through the front foot to stand. Alternate legs.',
    startPosition: 'Standing tall, dumbbells at your sides.',
    movementSequence: 'Step back, lower, drive up, switch legs.',
    cues: ['Torso tall', 'Front heel heavy'],
    mistakes: ['Dumbbells swinging', 'Back knee slamming down'],
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'adductors', 'forearms'],
    category: 'lunge',
    equipment: ['dumbbells'],
    impactLevel: 'low',
    easierVariantId: 'reverse-lunge',
  }),

  // ---------------------------------------------------------------------------
  // Hinge
  // ---------------------------------------------------------------------------
  ex({
    id: 'glute-bridge',
    name: 'Glute Bridge',
    description: 'Hip extension from the floor.',
    instructions: 'Drive through your heels to lift your hips until knees, hips and shoulders line up. Squeeze, then lower.',
    startPosition: 'Lying on your back, knees bent, feet flat and hip-width.',
    movementSequence: 'Lift the hips, pause, lower with control.',
    cues: ['Pause and squeeze at the top', 'Drive through the heels'],
    mistakes: ['Over-arching the low back', 'Pushing through the toes'],
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'abs'],
    category: 'hinge',
    equipment: ['mat'],
    impactLevel: 'low',
    harderVariantId: 'single-leg-bridge',
  }),
  ex({
    id: 'single-leg-bridge',
    name: 'Single-leg Bridge',
    description: 'Glute bridge on one leg.',
    instructions: 'With one foot planted and the other leg extended, bridge up on the working leg. Split reps evenly between legs.',
    startPosition: 'Glute bridge setup with one leg extended.',
    movementSequence: 'Bridge on one leg, lower, repeat; switch legs halfway.',
    cues: ['Keep the hips level', 'Push through the heel'],
    mistakes: ['Hip dropping on the free side'],
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'abs'],
    category: 'hinge',
    equipment: ['mat'],
    impactLevel: 'medium',
    easierVariantId: 'glute-bridge',
  }),
  ex({
    id: 'hip-thrust',
    name: 'Hip Thrust',
    description: 'Bench-supported hip extension with more range than a bridge.',
    instructions: 'Rest your upper back on a bench with feet flat, then drive your hips up until your torso is level, chin tucked. Lower under control.',
    startPosition: 'Seated on the floor, shoulder blades against the bench edge, knees bent.',
    movementSequence: 'Drive the hips up, squeeze, lower under control.',
    cues: ['Chin tucked, ribs down', 'Shins vertical at the top', 'Squeeze the glutes hard'],
    mistakes: ['Arching the low back to finish', 'Feet too far forward'],
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'quads'],
    category: 'hinge',
    equipment: ['bench'],
    impactLevel: 'low',
    easierVariantId: 'glute-bridge',
  }),
  ex({
    id: 'single-leg-deadlift',
    name: 'Single-leg Deadlift',
    description: 'Bodyweight hip hinge on one leg.',
    instructions: 'Hinge at the hip as the free leg reaches back, keeping the back flat, then return to standing. Split reps evenly between legs.',
    startPosition: 'Standing on one leg, soft knee.',
    movementSequence: 'Hinge until torso and back leg are near parallel to the floor, return to standing.',
    cues: ['Hips square', 'Long line from head to back heel'],
    mistakes: ['Opening the hips', 'Rounding the back'],
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['lower_back'],
    category: 'hinge',
    equipment: ['bodyweight'],
    impactLevel: 'low',
  }),
  ex({
    id: 'dumbbell-deadlift',
    name: 'Dumbbell Deadlift',
    description: 'Hip hinge lifting two dumbbells from the floor.',
    instructions: 'With dumbbells beside your feet, hinge with a flat back, grip, and stand up by driving the hips forward. Lower by pushing the hips back.',
    startPosition: 'Feet hip-width, dumbbells beside the feet, hips back, back flat.',
    movementSequence: 'Push the floor away, stand tall, hinge back down.',
    cues: ['Flat back', 'Push the floor away', 'Weights close to the legs'],
    mistakes: ['Rounding the back', 'Squatting the weight up instead of hinging'],
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['lower_back', 'forearms', 'quads'],
    category: 'hinge',
    equipment: ['dumbbells'],
    impactLevel: 'low',
  }),
  ex({
    id: 'dumbbell-snatch',
    name: 'Dumbbell Snatch',
    description: 'One-arm floor-to-overhead pull in a single explosive motion.',
    instructions: 'Hinge and grab one dumbbell between your feet, extend the hips hard, keep it close and punch it overhead to lockout. Alternate arms each rep.',
    startPosition: 'Feet hip-width, dumbbell on the floor between the feet, hinged with a flat back.',
    movementSequence: 'Extend the hips, pull high, punch under to lockout, lower to the floor.',
    cues: ['Hips do the work', 'Keep the bell close', 'Flat back at the bottom'],
    mistakes: ['Pulling with the arm only', 'Rounding the back to reach the floor'],
    primaryMuscles: ['glutes', 'hamstrings', 'shoulders'],
    secondaryMuscles: ['quads', 'upper_back', 'abs'],
    category: 'hinge',
    equipment: ['dumbbells'],
    impactLevel: 'medium',
  }),
  ex({
    id: 'kettlebell-deadlift',
    name: 'Kettlebell Deadlift',
    description: 'Hip hinge lifting a kettlebell from the floor.',
    instructions: 'With the kettlebell between your feet, push the hips back, grip the handle with a flat back and stand up tall. Lower by hinging back down.',
    startPosition: 'Feet hip-width, kettlebell between the arches.',
    movementSequence: 'Hinge, grip, stand tall, hinge back down.',
    cues: ['Flat back', 'Hips back first', 'Stand tall, glutes tight'],
    mistakes: ['Rounding the back', 'Squatting instead of hinging'],
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: ['lower_back', 'quads', 'forearms'],
    category: 'hinge',
    equipment: ['kettlebell'],
    impactLevel: 'low',
    harderVariantId: 'kettlebell-swing',
  }),
  ex({
    id: 'kettlebell-swing',
    name: 'Kettlebell Swing',
    description: 'Two-hand hip-hinge swing to chest height.',
    instructions: 'Hike the kettlebell back between your legs, then snap the hips forward so it floats to chest height. Let it fall back into the next hinge.',
    startPosition: 'Feet shoulder-width, kettlebell a foot in front, hinged with a flat back.',
    movementSequence: 'Hike back, drive the hips through, let the bell float, hinge as it returns.',
    cues: ["Hinge, don't squat", 'Snap the hips; the arms are just ropes', 'Squeeze the glutes at the top'],
    mistakes: ['Lifting with the arms', 'Rounding the low back', 'Leaning back at the top'],
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: ['lower_back', 'abs', 'shoulders', 'forearms'],
    category: 'hinge',
    equipment: ['kettlebell'],
    impactLevel: 'medium',
    easierVariantId: 'kettlebell-deadlift',
  }),

  // ---------------------------------------------------------------------------
  // Core
  // ---------------------------------------------------------------------------
  ex({
    id: 'mountain-climber',
    name: 'Mountain Climber',
    description: 'Running plank: fast alternating knee drives.',
    instructions: 'From a high plank, drive one knee toward your chest, then switch legs quickly. Each knee drive counts as one rep.',
    startPosition: 'High plank, shoulders over wrists.',
    movementSequence: 'Alternate fast knee drives while the hips stay level.',
    cues: ['Shoulders over wrists', 'Hips level with the shoulders'],
    mistakes: ['Bouncing hips', 'Hands creeping forward'],
    primaryMuscles: ['abs', 'hip_flexors'],
    secondaryMuscles: ['shoulders', 'quads'],
    category: 'core',
    equipment: ['bodyweight'],
    impactLevel: 'medium',
  }),
  ex({
    id: 'plank-hold',
    name: 'Plank Hold',
    description: 'Isometric front plank.',
    instructions: 'Hold a rigid line from head to heels on your forearms or hands. Breathe steadily without letting the hips sag or pike.',
    startPosition: 'Forearms under shoulders, legs straight, toes tucked.',
    movementSequence: 'Brace and hold for the full time.',
    cues: ['Squeeze the glutes', 'Ribs down', 'Push the floor away'],
    mistakes: ['Lower back arching', 'Holding your breath'],
    primaryMuscles: ['abs'],
    secondaryMuscles: ['obliques', 'shoulders', 'glutes'],
    category: 'core',
    equipment: ['mat'],
    impactLevel: 'low',
  }),
  ex({
    id: 'side-plank',
    name: 'Side Plank',
    description: 'Lateral plank for the obliques.',
    instructions: 'Stack your feet and lift the hips so your body forms a straight line. Switch sides halfway through the time.',
    startPosition: 'Side-lying, forearm under the shoulder, feet stacked.',
    movementSequence: 'Lift the hips and hold; switch sides halfway.',
    cues: ['Straight line from head to heels', 'Hips pushed forward, not back'],
    mistakes: ['Hips dropping', 'Shoulder collapsing toward the ear'],
    primaryMuscles: ['obliques'],
    secondaryMuscles: ['abs', 'glutes', 'shoulders'],
    category: 'core',
    equipment: ['mat'],
    impactLevel: 'low',
  }),
  ex({
    id: 'sit-up',
    name: 'Sit-up',
    description: 'Full trunk flexion from the floor.',
    instructions: 'Lie with knees bent and feet flat. Curl up until your chest reaches your knees, then lower with control.',
    startPosition: 'Lying on your back, knees bent, arms across the chest or overhead.',
    movementSequence: 'Curl up to seated, lower back down.',
    cues: ['Exhale as you rise', 'Lower slowly'],
    mistakes: ['Yanking on the neck', 'Flopping back down'],
    primaryMuscles: ['abs'],
    secondaryMuscles: ['hip_flexors'],
    category: 'core',
    equipment: ['mat'],
    impactLevel: 'low',
  }),
  ex({
    id: 'bicycle-crunch',
    name: 'Bicycle Crunch',
    description: 'Rotational crunch with a pedalling leg action.',
    instructions: 'Bring one elbow toward the opposite knee while the other leg extends, then switch. Each side counts as one rep.',
    startPosition: 'Lying on your back, hands lightly behind the head, legs in tabletop.',
    movementSequence: 'Rotate and pedal side to side.',
    cues: ['Rotate from the ribs', 'Slow and controlled', 'Low back stays down'],
    mistakes: ['Rushing reps', 'Pulling on the head'],
    primaryMuscles: ['abs', 'obliques'],
    secondaryMuscles: ['hip_flexors'],
    category: 'core',
    equipment: ['mat'],
    impactLevel: 'low',
  }),
  ex({
    id: 'leg-raise',
    name: 'Leg Raise',
    description: 'Lying straight-leg raise for the lower abs.',
    instructions: 'Keep your low back pressed down as you lift straight legs to vertical, then lower slowly without touching the floor.',
    startPosition: 'Lying on your back, legs straight, hands by your hips.',
    movementSequence: 'Lift the legs to 90°, lower with control.',
    cues: ['Press the low back into the floor', 'Lower slower than you lift'],
    mistakes: ['Swinging the legs', 'Low back arching off the floor'],
    primaryMuscles: ['abs'],
    secondaryMuscles: ['hip_flexors'],
    category: 'core',
    equipment: ['mat'],
    impactLevel: 'low',
  }),
  ex({
    id: 'v-up',
    name: 'V-up',
    description: 'Simultaneous trunk and leg lift into a V.',
    instructions: 'Lift straight arms and legs together and reach for your toes at the top, then lower both under control.',
    startPosition: 'Lying flat, arms overhead, legs straight.',
    movementSequence: 'Fold into a V, touch the toes, lower slowly.',
    cues: ['Reach long', 'Legs straight'],
    mistakes: ['Bent knees', 'Crashing back down'],
    primaryMuscles: ['abs'],
    secondaryMuscles: ['hip_flexors'],
    category: 'core',
    equipment: ['mat'],
    impactLevel: 'medium',
    easierVariantId: 'hollow-rock',
  }),
  ex({
    id: 'hollow-hold',
    name: 'Hollow Hold',
    description: 'Gymnastics hollow-body hold.',
    instructions: 'Press your low back into the floor and lift the shoulders and legs a few inches. Bend the knees to shorten the lever if your back peels up.',
    startPosition: 'Lying on your back, arms overhead.',
    movementSequence: 'Lift the shoulders and legs, hold the banana shape.',
    cues: ['Ribs down', 'Low back glued to the floor'],
    mistakes: ['Back peeling up', 'Chin jammed to the chest'],
    primaryMuscles: ['abs'],
    secondaryMuscles: ['hip_flexors'],
    category: 'core',
    equipment: ['mat'],
    impactLevel: 'low',
    harderVariantId: 'hollow-rock',
  }),
  ex({
    id: 'hollow-rock',
    name: 'Hollow Rock',
    description: 'Rocking back and forth in a hollow-body position.',
    instructions: 'Hold the hollow position and rock from shoulders to hips without losing the shape. Each rock forward and back counts as one rep.',
    startPosition: 'Hollow hold: low back pressed down, arms overhead, legs lifted.',
    movementSequence: 'Rock back and forth as one rigid piece.',
    cues: ['Stay banana-shaped', 'Arms and legs stay locked in place'],
    mistakes: ['Opening at the hips to create the rock', 'Low back peeling off the floor'],
    primaryMuscles: ['abs'],
    secondaryMuscles: ['hip_flexors', 'obliques'],
    category: 'core',
    equipment: ['mat'],
    impactLevel: 'low',
    easierVariantId: 'hollow-hold',
    harderVariantId: 'v-up',
  }),
  ex({
    id: 'superman-hold',
    name: 'Superman Hold',
    description: 'Face-down hold for the back of the body.',
    instructions: 'Lying face down, lift your arms, chest and legs off the floor and hold, keeping the neck long.',
    startPosition: 'Face down, arms overhead.',
    movementSequence: 'Lift and hold, breathing steadily.',
    cues: ['Glutes engaged', 'Eyes on the floor'],
    mistakes: ['Cranking the neck back', 'Bending the knees to fake height'],
    primaryMuscles: ['lower_back', 'glutes'],
    secondaryMuscles: ['upper_back', 'hamstrings'],
    category: 'core',
    equipment: ['mat'],
    impactLevel: 'low',
  }),
  ex({
    id: 'reverse-plank',
    name: 'Reverse Plank',
    description: 'Face-up plank for the glutes, hamstrings and shoulders.',
    instructions: 'Sit with legs straight and hands behind your hips, then lift the hips until your body forms a straight line. Hold with the shoulders away from the ears.',
    startPosition: 'Seated, legs straight, hands behind the hips with fingers toward the feet.',
    movementSequence: 'Lift the hips and hold the line.',
    cues: ['Squeeze the glutes', 'Chest open', 'Look up, not back'],
    mistakes: ['Hips sagging', 'Dropping the head back'],
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: ['lower_back', 'shoulders', 'triceps'],
    category: 'core',
    equipment: ['mat'],
    impactLevel: 'low',
  }),
  ex({
    id: 'flutter-kick',
    name: 'Flutter Kick',
    description: 'Small, fast alternating leg kicks on your back.',
    instructions: 'Lift straight legs a few inches and kick them up and down in small alternating strokes. Each kick counts as one rep.',
    startPosition: 'Lying on your back, hands under the hips.',
    movementSequence: 'Alternate small kicks with the low back pressed down.',
    cues: ['Belly tight', 'Small and fast'],
    mistakes: ['Huge kicks', 'Low back lifting'],
    primaryMuscles: ['abs'],
    secondaryMuscles: ['hip_flexors', 'quads'],
    category: 'core',
    equipment: ['mat'],
    impactLevel: 'low',
  }),
  ex({
    id: 'russian-twist',
    name: 'Russian Twist',
    description: 'Seated torso rotation.',
    instructions: 'Lean back slightly with a long spine and rotate side to side, touching the floor beside each hip. Each touch counts as one rep.',
    startPosition: 'Seated, knees bent, torso leaning back, feet down or lifted.',
    movementSequence: 'Rotate left and right.',
    cues: ['Rotate from the ribs', 'Chest tall'],
    mistakes: ['Only moving the arms', 'Rounding the back'],
    primaryMuscles: ['obliques'],
    secondaryMuscles: ['abs', 'hip_flexors'],
    category: 'core',
    equipment: ['mat'],
    impactLevel: 'low',
  }),
  ex({
    id: 'dead-bug',
    name: 'Dead Bug',
    description: 'Anti-extension core drill on your back.',
    instructions: 'Extend the opposite arm and leg toward the floor while the low back stays flat, return, and switch. Each side counts as one rep.',
    startPosition: 'Lying on your back, arms to the ceiling, knees over hips at 90°.',
    movementSequence: 'Extend opposite limbs, return, switch.',
    cues: ['Back flat', 'Exhale as you reach'],
    mistakes: ['Low back arching', 'Moving too fast'],
    primaryMuscles: ['abs'],
    secondaryMuscles: ['hip_flexors', 'obliques'],
    category: 'core',
    equipment: ['mat'],
    impactLevel: 'low',
  }),
  ex({
    id: 'bird-dog',
    name: 'Bird Dog',
    description: 'Opposite-arm-and-leg reach on all fours.',
    instructions: 'From all fours, reach one arm forward and the opposite leg back until both are level with your torso, pause, return and switch.',
    startPosition: 'All fours, hands under shoulders, knees under hips.',
    movementSequence: 'Reach long, pause, return, switch sides.',
    cues: ['Hips square to the floor', 'Reach long, not high'],
    mistakes: ['Rotating the hips', 'Arching the low back'],
    primaryMuscles: ['abs', 'lower_back'],
    secondaryMuscles: ['glutes', 'shoulders'],
    category: 'core',
    equipment: ['mat'],
    impactLevel: 'low',
  }),
  ex({
    id: 'plank-to-push-up',
    name: 'Plank to Push-up',
    description: 'Walk up from forearms to hands and back down.',
    instructions: 'From a forearm plank, press up one hand at a time to a high plank, then lower back to the forearms. Each up-and-down counts as one rep; alternate the lead arm.',
    startPosition: 'Forearm plank, feet a little wider than the hips.',
    movementSequence: 'Press up to the hands, lower to the forearms, switch the lead arm.',
    cues: ['Minimize hip sway', 'Feet wide for stability'],
    mistakes: ['Rocking the hips side to side', 'Hips piking'],
    primaryMuscles: ['abs', 'triceps'],
    secondaryMuscles: ['shoulders', 'chest'],
    category: 'core',
    equipment: ['bodyweight'],
    impactLevel: 'medium',
  }),
  ex({
    id: 'shoulder-tap',
    name: 'Shoulder Tap',
    description: 'High plank with alternating shoulder taps.',
    instructions: 'Hold a high plank and tap each hand to the opposite shoulder while keeping the hips still. Each tap counts as one rep.',
    startPosition: 'High plank, feet wider than the hips.',
    movementSequence: 'Alternate taps with minimal sway.',
    cues: ['Feet wide for stability', 'Squeeze the glutes'],
    mistakes: ['Hips rotating with each tap'],
    primaryMuscles: ['abs', 'obliques'],
    secondaryMuscles: ['shoulders', 'triceps'],
    category: 'core',
    equipment: ['bodyweight'],
    impactLevel: 'low',
  }),
  ex({
    id: 'hanging-knee-raise',
    name: 'Hanging Knee Raise',
    description: 'Hang from the bar and drive the knees to the chest.',
    instructions: 'From a dead hang, curl your knees up toward your chest with control, then lower without swinging.',
    startPosition: 'Dead hang, legs together.',
    movementSequence: 'Lift the knees to at least hip height, lower slowly.',
    cues: ['Tuck the pelvis at the top', 'Control the swing'],
    mistakes: ['Swinging for momentum', 'Knees stopping below hip height'],
    primaryMuscles: ['abs', 'hip_flexors'],
    secondaryMuscles: ['forearms', 'lats', 'obliques'],
    category: 'core',
    equipment: ['pull-up-bar'],
    impactLevel: 'low',
    easierVariantId: 'leg-raise',
    harderVariantId: 'toes-to-bar',
  }),
  ex({
    id: 'toes-to-bar',
    name: 'Toes-to-bar',
    description: 'Hanging leg raise until the toes touch the bar.',
    instructions: 'From a dead hang, press the bar down with straight arms and lift your feet to touch the bar between your hands, then lower with control.',
    startPosition: 'Dead hang, legs together.',
    movementSequence: 'Lift the feet to the bar, touch, lower back under the bar.',
    cues: ['Push the bar toward your hips', 'Feet together', 'Control the descent'],
    mistakes: ['Wild swinging between reps', 'Bending the arms'],
    primaryMuscles: ['abs', 'hip_flexors'],
    secondaryMuscles: ['lats', 'forearms', 'obliques'],
    category: 'core',
    equipment: ['pull-up-bar'],
    impactLevel: 'medium',
    easierVariantId: 'hanging-knee-raise',
  }),

  // ---------------------------------------------------------------------------
  // Cardio
  // ---------------------------------------------------------------------------
  ex({
    id: 'high-knees',
    name: 'High Knees',
    description: 'Sprint in place with the knees to hip height.',
    instructions: 'Run on the spot, driving the knees to hip height and pumping the arms. Each knee counts as one rep.',
    startPosition: 'Standing tall.',
    movementSequence: 'Fast alternating knee drives on the balls of the feet.',
    cues: ['Pump the arms', 'Stay tall'],
    mistakes: ['Leaning back', 'Knees barely leaving the floor'],
    primaryMuscles: ['hip_flexors', 'quads'],
    secondaryMuscles: ['calves', 'abs'],
    category: 'cardio',
    equipment: ['bodyweight'],
    impactLevel: 'medium',
  }),
  ex({
    id: 'butt-kicks',
    name: 'Butt Kicks',
    description: 'Jog in place, heels flicking up to the glutes.',
    instructions: 'Jog on the spot with quick feet, flicking each heel up toward your glutes. Each kick counts as one rep.',
    startPosition: 'Standing tall.',
    movementSequence: 'Quick alternating heel kicks.',
    cues: ['Upright torso', 'Quick, light feet'],
    mistakes: ['Leaning forward', 'Heavy heel strikes'],
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['calves', 'glutes'],
    category: 'cardio',
    equipment: ['bodyweight'],
    impactLevel: 'medium',
  }),
  ex({
    id: 'jumping-jack',
    name: 'Jumping Jack',
    description: 'The classic jump-out, jump-in cardio opener.',
    instructions: 'Jump the feet wide as the arms sweep overhead, then jump back together. Each full out-and-in counts as one rep.',
    startPosition: 'Standing, feet together, arms by your sides.',
    movementSequence: 'Jump out with the arms overhead, jump back in.',
    cues: ['Soft landings', 'Stay on the balls of the feet'],
    mistakes: ['Stiff knees', 'Flat-footed landings'],
    primaryMuscles: ['calves', 'shoulders'],
    secondaryMuscles: ['glutes', 'adductors'],
    category: 'cardio',
    equipment: ['bodyweight'],
    impactLevel: 'medium',
    harderVariantId: 'star-jump',
  }),
  ex({
    id: 'star-jump',
    name: 'Star Jump',
    description: 'Explosive jump that spreads the arms and legs into a star.',
    instructions: 'Dip into a quarter squat, jump up spreading the arms and legs into an X, then bring them back together to land softly.',
    startPosition: 'Standing, feet together, in a slight crouch.',
    movementSequence: 'Crouch, jump into a star, land with the feet together, reset.',
    cues: ['Land with soft knees', 'Full spread at the top'],
    mistakes: ['Landing with straight legs', 'Arching the back in the air'],
    primaryMuscles: ['quads', 'calves'],
    secondaryMuscles: ['glutes', 'shoulders'],
    category: 'cardio',
    equipment: ['bodyweight'],
    impactLevel: 'high',
    easierVariantId: 'jumping-jack',
  }),
  ex({
    id: 'seal-jack',
    name: 'Seal Jack',
    description: 'Jumping jack with a horizontal arm clap.',
    instructions: 'Jump the feet wide while opening the arms out to the sides, then jump in and clap your hands in front of your chest.',
    startPosition: 'Standing, arms extended in front at chest height.',
    movementSequence: 'Jump wide with the arms open, jump in with a clap.',
    cues: ['Stay light on your feet', 'Open the chest fully'],
    mistakes: ['Arms doing all the work', 'Landing on the heels'],
    primaryMuscles: ['calves', 'shoulders'],
    secondaryMuscles: ['chest', 'upper_back'],
    category: 'cardio',
    equipment: ['bodyweight'],
    impactLevel: 'medium',
  }),
  ex({
    id: 'skater-hop',
    name: 'Skater Hop',
    description: 'Lateral bound from one foot to the other.',
    instructions: 'Leap sideways and land on the outside foot, letting the trail leg sweep behind, then bound back the other way. Each landing counts as one rep.',
    startPosition: 'Standing on one leg, slight knee bend.',
    movementSequence: 'Bound laterally, land softly, reverse.',
    cues: ['Bend the landing knee', 'Stick each landing'],
    mistakes: ['Short bounds', 'Knee caving on landing'],
    primaryMuscles: ['glutes', 'quads'],
    secondaryMuscles: ['calves', 'adductors'],
    category: 'cardio',
    equipment: ['bodyweight'],
    impactLevel: 'high',
  }),
  ex({
    id: 'side-shuffle',
    name: 'Side Shuffle',
    description: 'Low, quick lateral shuffle.',
    instructions: 'In a quarter squat, shuffle sideways without crossing your feet, changing direction every few steps. Each step counts as one rep.',
    startPosition: 'Athletic quarter squat.',
    movementSequence: 'Shuffle left and right.',
    cues: ['Stay low', 'Push off the trailing foot'],
    mistakes: ['Crossing the feet', 'Standing up tall'],
    primaryMuscles: ['glutes', 'quads'],
    secondaryMuscles: ['adductors', 'calves'],
    category: 'cardio',
    equipment: ['bodyweight'],
    impactLevel: 'medium',
  }),
  ex({
    id: 'jump-rope',
    name: 'Jump Rope',
    description: 'Single-unders with a rope.',
    instructions: 'Turn the rope from the wrists and take small hops on the balls of your feet. Each turn counts as one rep.',
    startPosition: 'Standing with the rope behind your heels.',
    movementSequence: 'Rhythmic small jumps, one per turn.',
    cues: ['Elbows in', 'Turn from the wrists', 'Small hops'],
    mistakes: ['Jumping too high', 'Swinging from the shoulders'],
    primaryMuscles: ['calves'],
    secondaryMuscles: ['shoulders', 'forearms', 'quads'],
    category: 'cardio',
    equipment: ['jump-rope'],
    impactLevel: 'medium',
  }),

  // ---------------------------------------------------------------------------
  // Conditioning
  // ---------------------------------------------------------------------------
  ex({
    id: 'burpee',
    name: 'Burpee',
    description: 'Chest to the floor, jump to finish: the full-body conditioning staple.',
    instructions: 'Drop your hands, jump or step back to a plank, lower your chest to the floor, push up, bring your feet in and jump with a clap overhead.',
    startPosition: 'Standing, feet shoulder-width.',
    movementSequence: 'Squat, kick back, chest to the floor, push up, feet in, jump.',
    cues: ['Exhale on the effort', 'Land the feet under the hips', 'Find a rhythm, not a sprint'],
    mistakes: ['Skipping the chest to the floor', 'Sagging low back in the plank'],
    primaryMuscles: ['chest', 'quads', 'shoulders'],
    secondaryMuscles: ['glutes', 'triceps', 'abs', 'calves'],
    category: 'conditioning',
    equipment: ['bodyweight'],
    impactLevel: 'high',
    easierVariantId: 'half-burpee',
  }),
  ex({
    id: 'half-burpee',
    name: 'Half Burpee',
    description: 'Burpee without the push-up or the big jump.',
    instructions: 'Squat, place your hands, step or jump back to a plank, return your feet to your hands and stand up.',
    startPosition: 'Standing, feet shoulder-width.',
    movementSequence: 'Squat, plank, feet in, stand or small hop.',
    cues: ['Core tight in the plank', 'Step instead of jumping if you need to'],
    mistakes: ['Hips sagging in the plank', 'Rounding hard through the back to reach the floor'],
    primaryMuscles: ['quads', 'shoulders'],
    secondaryMuscles: ['glutes', 'abs', 'chest'],
    category: 'conditioning',
    equipment: ['bodyweight'],
    impactLevel: 'medium',
    harderVariantId: 'burpee',
  }),
  ex({
    id: 'bear-crawl',
    name: 'Bear Crawl',
    description: 'Crawl on hands and feet with the knees hovering.',
    instructions: 'From all fours, lift the knees an inch off the floor and move opposite hand and foot together, forward, back or in place.',
    startPosition: 'All fours, knees hovering just off the floor.',
    movementSequence: 'Crawl with opposite hand and foot moving together.',
    cues: ['Quiet hips', 'Knees low', 'Short steps'],
    mistakes: ['Hips swaying side to side', 'Hips shooting up high'],
    primaryMuscles: ['shoulders', 'abs'],
    secondaryMuscles: ['quads', 'hip_flexors'],
    category: 'conditioning',
    equipment: ['bodyweight'],
    impactLevel: 'medium',
  }),
  ex({
    id: 'crab-walk',
    name: 'Crab Walk',
    description: 'Face-up tabletop walk.',
    instructions: 'Sit, place your hands behind you, lift the hips and walk on hands and feet forward and back.',
    startPosition: 'Seated, hands behind you with fingers forward, hips lifted.',
    movementSequence: 'Walk forward or back with the hips staying up.',
    cues: ['Chest open', 'Hips high'],
    mistakes: ['Hips dropping to the floor', 'Shoulders rolling forward'],
    primaryMuscles: ['triceps', 'glutes'],
    secondaryMuscles: ['shoulders', 'hamstrings'],
    category: 'conditioning',
    equipment: ['bodyweight'],
    impactLevel: 'medium',
  }),
  ex({
    id: 'inchworm',
    name: 'Inchworm',
    description: 'Walk out to a plank and back.',
    instructions: 'Fold forward, walk your hands out to a high plank, then walk your feet up toward your hands and stand.',
    startPosition: 'Standing tall.',
    movementSequence: 'Fold, walk out to a plank, walk the feet in, stand.',
    cues: ['Legs as straight as is comfortable', 'Brace in the plank'],
    mistakes: ['Hips sagging in the plank', 'Rushing the walk-out'],
    primaryMuscles: ['abs', 'shoulders'],
    secondaryMuscles: ['hamstrings', 'chest'],
    category: 'conditioning',
    equipment: ['bodyweight'],
    impactLevel: 'low',
  }),
  ex({
    id: 'broad-jump',
    name: 'Broad Jump',
    description: 'Standing horizontal jump for power.',
    instructions: 'Swing the arms, load the hips and jump forward as far as you can, sticking a balanced landing. Turn around or walk back between reps if space is tight.',
    startPosition: 'Standing, feet hip-width.',
    movementSequence: 'Countermovement, jump forward, stick the landing.',
    cues: ['Land balanced with soft knees', 'Swing hard with the arms'],
    mistakes: ['Falling forward on landing', 'Knees caving'],
    primaryMuscles: ['glutes', 'quads'],
    secondaryMuscles: ['hamstrings', 'calves'],
    category: 'conditioning',
    equipment: ['bodyweight'],
    impactLevel: 'high',
  }),
  ex({
    id: 'plank-jack',
    name: 'Plank Jack',
    description: 'Jumping jack for the feet, held in a high plank.',
    instructions: 'Hold a high plank and jump the feet wide and back together. Each out-and-in counts as one rep.',
    startPosition: 'High plank, feet together.',
    movementSequence: 'Jump the feet wide, jump back in.',
    cues: ['Hips stable', 'Shoulders over wrists'],
    mistakes: ['Bouncing hips', 'Piking up'],
    primaryMuscles: ['abs', 'shoulders'],
    secondaryMuscles: ['glutes', 'adductors', 'calves'],
    category: 'conditioning',
    equipment: ['bodyweight'],
    impactLevel: 'medium',
  }),
  ex({
    id: 'sprawl',
    name: 'Sprawl',
    description: 'Fast drop to the floor and back up, without a push-up or jump.',
    instructions: 'Drop the hands, shoot the feet back and lower the hips to the floor, then snap the feet back in and stand.',
    startPosition: 'Standing in an athletic stance.',
    movementSequence: 'Hands down, feet back, hips down, feet in, stand.',
    cues: ['Hips low', 'Fast feet'],
    mistakes: ['Slow feet', 'Sagging into the low back'],
    primaryMuscles: ['quads', 'shoulders'],
    secondaryMuscles: ['abs', 'glutes', 'chest'],
    category: 'conditioning',
    equipment: ['bodyweight'],
    impactLevel: 'medium',
  }),
  ex({
    id: 'squat-thrust',
    name: 'Squat Thrust',
    description: 'Squat, kick back to a plank, return.',
    instructions: 'Squat and place your hands down, jump the feet back to a plank, jump them back in and stand.',
    startPosition: 'Standing.',
    movementSequence: 'Squat, thrust back, feet in, stand.',
    cues: ['Core tight', 'Land the feet flat beside the hands'],
    mistakes: ['Hips high in the plank', 'Not standing all the way up'],
    primaryMuscles: ['quads', 'shoulders'],
    secondaryMuscles: ['abs', 'glutes'],
    category: 'conditioning',
    equipment: ['bodyweight'],
    impactLevel: 'medium',
  }),
  ex({
    id: 'tuck-jump',
    name: 'Tuck Jump',
    description: 'Max-height jump pulling the knees to the chest.',
    instructions: 'Jump straight up, drive the knees toward your chest at the top, open back out and land softly.',
    startPosition: 'Standing, feet hip-width.',
    movementSequence: 'Dip, jump, tuck, land softly, reset.',
    cues: ['Drive the knees up, not the chest down', 'Quiet landings', 'Reset if you lose rhythm'],
    mistakes: ['Stiff landings', 'Rounding forward to meet the knees'],
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['calves', 'hip_flexors', 'abs'],
    category: 'conditioning',
    equipment: ['bodyweight'],
    impactLevel: 'high',
    easierVariantId: 'jump-squat',
  }),
  ex({
    id: 'devil-press',
    name: 'Devil Press',
    description: 'Dumbbell burpee into a double-dumbbell swing to overhead.',
    instructions: 'Hands on two dumbbells, jump back and lower your chest to the floor, jump the feet in, then hinge and swing both dumbbells from the floor to overhead in one motion.',
    startPosition: 'Standing over two dumbbells.',
    movementSequence: 'Burpee onto the dumbbells, feet in, hinge, swing overhead, lower.',
    cues: ['Use the hips, not the arms', 'Flat back as you grab the bells', 'Breathe at the top'],
    mistakes: ['Rounding the back off the floor', 'Muscling the press with the arms'],
    primaryMuscles: ['shoulders', 'glutes', 'hamstrings'],
    secondaryMuscles: ['chest', 'quads', 'triceps', 'abs'],
    category: 'conditioning',
    equipment: ['dumbbells'],
    impactLevel: 'high',
  }),
  ex({
    id: 'farmer-carry',
    name: 'Farmer Carry',
    description: 'Walk tall holding heavy dumbbells at your sides.',
    instructions: 'Pick up a heavy dumbbell in each hand and walk with short, controlled steps, standing tall. Walk laps or march in place if space is tight.',
    startPosition: 'Standing tall, dumbbells at your sides.',
    movementSequence: 'Walk with short steps for the full time, then set the dumbbells down with a flat back.',
    cues: ['Shoulders down and back', 'Crush the handles', 'Tall posture'],
    mistakes: ['Leaning to one side', 'Rounding the back on the pickup'],
    primaryMuscles: ['forearms', 'upper_back'],
    secondaryMuscles: ['abs', 'obliques', 'glutes', 'calves'],
    category: 'conditioning',
    equipment: ['dumbbells'],
    impactLevel: 'low',
  }),

  // ---------------------------------------------------------------------------
  // Accessory
  // ---------------------------------------------------------------------------
  ex({
    id: 'calf-raise',
    name: 'Calf Raise',
    description: 'Standing heel raise.',
    instructions: 'Rise onto the balls of your feet as high as you can, pause, and lower slowly to full heel contact.',
    startPosition: 'Standing, feet hip-width, a wall nearby for balance.',
    movementSequence: 'Lift the heels, pause, lower with control.',
    cues: ['Full range', 'Pause at the top'],
    mistakes: ['Bouncing', 'Rolling onto the outside of the foot'],
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    category: 'accessory',
    equipment: ['bodyweight'],
    impactLevel: 'low',
  }),
  ex({
    id: 'dumbbell-curl',
    name: 'Dumbbell Curl',
    description: 'Biceps curl with two dumbbells.',
    instructions: 'With the elbows pinned to your sides, curl the dumbbells to your shoulders and lower slowly.',
    startPosition: 'Standing, dumbbells at your sides, palms forward.',
    movementSequence: 'Curl up, squeeze, lower under control.',
    cues: ['Elbows stay pinned', 'Lower slower than you lift'],
    mistakes: ['Swinging the torso'],
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    category: 'accessory',
    equipment: ['dumbbells'],
    impactLevel: 'low',
  }),
  ex({
    id: 'lateral-raise',
    name: 'Lateral Raise',
    description: 'Side raise for the shoulders.',
    instructions: 'With a slight bend in the elbows, raise light dumbbells out to the sides to shoulder height and lower slowly.',
    startPosition: 'Standing, dumbbells at your sides.',
    movementSequence: 'Raise to shoulder height, pause, lower.',
    cues: ['Lead with the elbows', 'Light weight, strict reps'],
    mistakes: ['Shrugging the weights up', 'Swinging the torso'],
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['upper_back'],
    category: 'accessory',
    equipment: ['dumbbells'],
    impactLevel: 'low',
  }),
  ex({
    id: 'kettlebell-halo',
    name: 'Kettlebell Halo',
    description: 'Circle a kettlebell around your head for shoulder control.',
    instructions: 'Hold the kettlebell upside down by the horns and circle it slowly around your head, keeping it close. Alternate direction each rep.',
    startPosition: 'Standing, kettlebell held by the horns at chest height.',
    movementSequence: 'Circle around the head, return to the chest, reverse.',
    cues: ['Ribs down', 'Keep the bell close to the head'],
    mistakes: ['Arching the low back', 'Rushing the circle'],
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['upper_back', 'triceps', 'abs'],
    category: 'accessory',
    equipment: ['kettlebell'],
    impactLevel: 'low',
  }),

  // ---------------------------------------------------------------------------
  // Mobility and recovery
  // ---------------------------------------------------------------------------
  ex({
    id: 'cat-cow',
    name: 'Cat-Cow',
    description: 'Slow spinal flexion and extension on all fours.',
    instructions: 'On all fours, round your back toward the ceiling as you exhale, then let the belly drop and lift the chest as you inhale. Move with the breath.',
    startPosition: 'All fours, hands under shoulders, knees under hips.',
    movementSequence: 'Round up (cat), arch down (cow), repeat slowly.',
    cues: ['Move one vertebra at a time', 'Breathe with the movement'],
    mistakes: ['Rushing the reps', 'Only moving the neck'],
    primaryMuscles: ['lower_back', 'upper_back'],
    secondaryMuscles: ['abs'],
    category: 'mobility',
    equipment: ['mat'],
    impactLevel: 'low',
  }),
  ex({
    id: 'worlds-greatest-stretch',
    name: "World's Greatest Stretch",
    description: 'Lunge, elbow-to-instep and upper-back rotation in one flow.',
    instructions: 'Step into a deep lunge, drop the inside elbow toward the front foot, then rotate and reach that arm to the ceiling. Alternate sides each rep.',
    startPosition: 'Deep lunge, hands on the floor inside the front foot.',
    movementSequence: 'Elbow to instep, rotate and reach up, return, switch legs.',
    cues: ['Back leg long and active', 'Follow the top hand with your eyes'],
    mistakes: ['Back knee collapsing to the floor', 'Rushing the rotation'],
    primaryMuscles: ['hip_flexors', 'hamstrings', 'upper_back'],
    secondaryMuscles: ['glutes', 'adductors', 'obliques'],
    category: 'mobility',
    equipment: ['bodyweight'],
    impactLevel: 'low',
  }),
  ex({
    id: 'hip-flexor-stretch',
    name: 'Half-kneeling Hip Flexor Stretch',
    description: 'Half-kneeling stretch for the front of the hip.',
    instructions: 'Kneel on one knee with the other foot forward, tuck your pelvis and shift forward gently until the front of the back hip opens. Switch sides halfway.',
    startPosition: 'Half-kneeling, back knee on a mat, front shin vertical.',
    movementSequence: 'Tuck the pelvis, shift forward, hold; switch sides halfway.',
    cues: ['Squeeze the glute of the back leg', 'Ribs down, tall torso'],
    mistakes: ['Arching the low back instead of tucking', 'Lunging too deep'],
    primaryMuscles: ['hip_flexors'],
    secondaryMuscles: ['quads'],
    category: 'mobility',
    equipment: ['mat'],
    impactLevel: 'low',
  }),
  ex({
    id: 'downward-dog',
    name: 'Downward Dog',
    description: 'Inverted V that lengthens the calves, hamstrings and shoulders.',
    instructions: 'From all fours, lift your hips up and back into an inverted V, pressing your chest toward your thighs. Pedal the heels gently if the calves are tight.',
    startPosition: 'All fours, toes tucked.',
    movementSequence: 'Lift the hips, press back, hold and breathe.',
    cues: ['Push the floor away', 'Long spine before straight legs', 'Heels reach toward the floor'],
    mistakes: ['Rounding the back to straighten the knees', 'Shrugging into the ears'],
    primaryMuscles: ['hamstrings', 'calves'],
    secondaryMuscles: ['shoulders', 'lats'],
    category: 'mobility',
    equipment: ['mat'],
    impactLevel: 'low',
  }),
  ex({
    id: 'child-pose',
    name: "Child's Pose",
    description: 'Resting stretch for the back, lats and hips.',
    instructions: 'Kneel, sit your hips back toward your heels and walk your hands forward, letting your chest sink toward the floor. Breathe slowly into your back.',
    startPosition: 'Kneeling, knees wide, big toes touching.',
    movementSequence: 'Sit back, reach forward, relax and breathe.',
    cues: ['Hips sink toward the heels', 'Long, slow exhales'],
    mistakes: ['Holding tension in the shoulders'],
    primaryMuscles: ['lower_back', 'lats'],
    secondaryMuscles: ['glutes', 'shoulders'],
    category: 'mobility',
    equipment: ['mat'],
    impactLevel: 'low',
  }),
  ex({
    id: 'cobra-stretch',
    name: 'Cobra Stretch',
    description: 'Gentle face-down back extension that opens the chest and abs.',
    instructions: 'Lying face down with hands under your shoulders, press the chest up while the hips stay on the floor. Only go as high as feels comfortable for your low back.',
    startPosition: 'Face down, hands under the shoulders, legs long.',
    movementSequence: 'Press the chest up, hold and breathe, lower.',
    cues: ['Shoulders down, away from the ears', 'Hips stay heavy'],
    mistakes: ['Forcing a deep arch', 'Locking the elbows and shrugging'],
    primaryMuscles: ['abs', 'lower_back'],
    secondaryMuscles: ['chest', 'hip_flexors'],
    category: 'mobility',
    equipment: ['mat'],
    impactLevel: 'low',
  }),
  ex({
    id: 'arm-circles',
    name: 'Arm Circles',
    description: 'Controlled shoulder circles that grow in size.',
    instructions: 'Arms out to the sides, draw small circles and gradually make them bigger; reverse direction halfway.',
    startPosition: 'Standing, arms out at shoulder height.',
    movementSequence: 'Small to big circles forward, then backward.',
    cues: ['Relaxed neck', 'Slow, full circles'],
    mistakes: ['Shrugging', 'Flailing fast and small'],
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['upper_back', 'chest'],
    category: 'mobility',
    equipment: ['bodyweight'],
    impactLevel: 'low',
  }),
  ex({
    id: 'leg-swings',
    name: 'Leg Swings',
    description: 'Dynamic forward and side leg swings to open the hips.',
    instructions: 'Hold a wall for balance and swing one leg forward and back, then side to side, letting the range grow. Switch legs halfway.',
    startPosition: 'Standing side-on to a wall, one hand on it.',
    movementSequence: 'Swing forward and back, then across the body; switch legs.',
    cues: ['Stand tall on the support leg', 'Let the range build gradually'],
    mistakes: ['Forcing the end range', 'Rounding the back to kick higher'],
    primaryMuscles: ['hip_flexors', 'hamstrings'],
    secondaryMuscles: ['adductors', 'glutes'],
    category: 'mobility',
    equipment: ['bodyweight'],
    impactLevel: 'low',
  }),
  ex({
    id: 'open-book',
    name: 'Open Book',
    description: 'Side-lying rotation for the upper back.',
    instructions: 'Lying on your side with knees bent, rotate the top arm open toward the floor behind you, following it with your eyes, then close. Switch sides halfway.',
    startPosition: 'Side-lying, knees bent to 90°, arms straight in front and together.',
    movementSequence: 'Open the top arm like a book, pause, close, repeat.',
    cues: ['Knees stay stacked', 'Rotate through the upper back'],
    mistakes: ['Knees lifting apart', 'Forcing the arm to the floor'],
    primaryMuscles: ['upper_back', 'chest'],
    secondaryMuscles: ['obliques', 'shoulders'],
    category: 'mobility',
    equipment: ['mat'],
    impactLevel: 'low',
  }),
  ex({
    id: 'box-breather',
    name: 'Box Breather',
    description: 'Four-count breathing to bring the heart rate down.',
    instructions: 'Inhale for four counts, hold for four, exhale for four, hold for four. Repeat for the full time.',
    startPosition: 'Seated or standing tall, shoulders relaxed.',
    movementSequence: 'Controlled breathing cycle: in, hold, out, hold.',
    cues: ['Inhale through the nose if you can', 'Let the belly expand'],
    mistakes: ['Shallow chest breathing', 'Forcing the holds'],
    primaryMuscles: ['abs'],
    secondaryMuscles: [],
    category: 'recovery',
    equipment: ['bodyweight'],
    impactLevel: 'low',
  }),
];
