import type { WorkoutStructure } from '../domain/types';

export interface ExerciseSeed {
  id: string;
  name: string;
  description: string;
  instructions: string;
  startPosition: string;
  movementSequence: string;
  cues: string[];
  mistakes: string[];
  primaryMuscles: string[];
  secondaryMuscles: string[];
  category: string;
  equipment: string[];
  impactLevel: 'low' | 'medium' | 'high';
  easierVariantId?: string;
  harderVariantId?: string;
  visualAsset: string;
}

export const EXERCISE_SEEDS: ExerciseSeed[] = [
  { id: 'wall-push-up', name: 'Wall Push-up', description: 'Incline push pattern against a wall.', instructions: 'Stand arm\'s length from wall, hands at chest height.', startPosition: 'Stand facing wall, palms flat.', movementSequence: 'Bend elbows to bring chest toward wall, press back.', cues: ['Brace core', 'Elbows at 45°'], mistakes: ['Sagging hips'], primaryMuscles: ['Chest'], secondaryMuscles: ['Triceps', 'Shoulders'], category: 'push', equipment: ['bodyweight'], impactLevel: 'low', harderVariantId: 'knee-push-up', visualAsset: 'exercises/wall-push-up' },
  { id: 'knee-push-up', name: 'Knee Push-up', description: 'Scaled push-up from knees.', instructions: 'Knees down, hands under shoulders.', startPosition: 'High plank from knees.', movementSequence: 'Lower chest between hands, press up.', cues: ['Straight line knee to head'], mistakes: ['Hips piking up'], primaryMuscles: ['Chest'], secondaryMuscles: ['Triceps'], category: 'push', equipment: ['mat'], impactLevel: 'low', easierVariantId: 'wall-push-up', harderVariantId: 'push-up', visualAsset: 'exercises/knee-push-up' },
  { id: 'push-up', name: 'Push-up', description: 'Standard floor push-up.', instructions: 'Hands shoulder-width, full body plank.', startPosition: 'High plank.', movementSequence: 'Lower chest to floor, full extension up.', cues: ['Ribs down', 'Glutes tight'], mistakes: ['Partial range'], primaryMuscles: ['Chest'], secondaryMuscles: ['Triceps', 'Core'], category: 'push', equipment: ['bodyweight'], impactLevel: 'medium', easierVariantId: 'knee-push-up', harderVariantId: 'decline-push-up', visualAsset: 'exercises/push-up' },
  { id: 'decline-push-up', name: 'Decline Push-up', description: 'Feet elevated push-up.', instructions: 'Feet on bench or step.', startPosition: 'Plank with feet elevated.', movementSequence: 'Lower under control, press up.', cues: ['Control descent'], mistakes: ['Bouncing at bottom'], primaryMuscles: ['Chest'], secondaryMuscles: ['Shoulders'], category: 'push', equipment: ['bench'], impactLevel: 'medium', easierVariantId: 'push-up', visualAsset: 'exercises/decline-push-up' },
  { id: 'pike-push-up', name: 'Pike Push-up', description: 'Shoulder-focused push pattern.', instructions: 'Hips high, head travels forward-down.', startPosition: 'Downward dog style pike.', movementSequence: 'Bend elbows, head toward floor, press up.', cues: ['Look between hands'], mistakes: ['Elbows flaring wide'], primaryMuscles: ['Shoulders'], secondaryMuscles: ['Triceps'], category: 'push', equipment: ['bodyweight'], impactLevel: 'medium', visualAsset: 'exercises/pike-push-up' },
  { id: 'diamond-push-up', name: 'Diamond Push-up', description: 'Tricep-biased push-up.', instructions: 'Hands form diamond under chest.', startPosition: 'Plank, hands together.', movementSequence: 'Lower chest to hands, press up.', cues: ['Elbows track back'], mistakes: ['Hands too far forward'], primaryMuscles: ['Triceps'], secondaryMuscles: ['Chest'], category: 'push', equipment: ['bodyweight'], impactLevel: 'medium', easierVariantId: 'push-up', visualAsset: 'exercises/diamond-push-up' },
  { id: 'air-squat', name: 'Air Squat', description: 'Bodyweight squat.', instructions: 'Feet shoulder-width, sit hips back and down.', startPosition: 'Standing tall.', movementSequence: 'Squat to thighs parallel, stand.', cues: ['Knees track toes', 'Chest up'], mistakes: ['Heels lifting'], primaryMuscles: ['Quads'], secondaryMuscles: ['Glutes'], category: 'squat', equipment: ['bodyweight'], impactLevel: 'low', harderVariantId: 'jump-squat', visualAsset: 'exercises/air-squat' },
  { id: 'jump-squat', name: 'Jump Squat', description: 'Explosive squat with jump.', instructions: 'Squat then drive through floor to jump.', startPosition: 'Standing.', movementSequence: 'Squat, explode up, land soft.', cues: ['Soft landing'], mistakes: ['Landing stiff'], primaryMuscles: ['Quads'], secondaryMuscles: ['Glutes', 'Calves'], category: 'squat', equipment: ['bodyweight'], impactLevel: 'high', easierVariantId: 'air-squat', visualAsset: 'exercises/jump-squat' },
  { id: 'walking-lunge', name: 'Walking Lunge', description: 'Alternating forward lunges.', instructions: 'Step long, back knee kisses floor.', startPosition: 'Standing.', movementSequence: 'Lunge right, then left, continue.', cues: ['Torso upright'], mistakes: ['Short steps'], primaryMuscles: ['Quads'], secondaryMuscles: ['Glutes'], category: 'lunge', equipment: ['bodyweight'], impactLevel: 'medium', easierVariantId: 'reverse-lunge', harderVariantId: 'jumping-lunge', visualAsset: 'exercises/walking-lunge' },
  { id: 'reverse-lunge', name: 'Reverse Lunge', description: 'Step back lunge pattern.', instructions: 'Step back, lower, return.', startPosition: 'Standing.', movementSequence: 'Step back into lunge, drive up.', cues: ['Front shin vertical'], mistakes: ['Leaning forward'], primaryMuscles: ['Quads'], secondaryMuscles: ['Glutes'], category: 'lunge', equipment: ['bodyweight'], impactLevel: 'low', harderVariantId: 'walking-lunge', visualAsset: 'exercises/reverse-lunge' },
  { id: 'jumping-lunge', name: 'Jumping Lunge', description: 'Alternating jump lunges.', instructions: 'Switch legs in air.', startPosition: 'Lunge position.', movementSequence: 'Jump and switch, land soft.', cues: ['Absorb landing'], mistakes: ['Knee collapse'], primaryMuscles: ['Quads'], secondaryMuscles: ['Glutes'], category: 'lunge', equipment: ['bodyweight'], impactLevel: 'high', easierVariantId: 'walking-lunge', visualAsset: 'exercises/jumping-lunge' },
  { id: 'burpee', name: 'Burpee', description: 'Full body conditioning move.', instructions: 'Drop to floor, chest down, jump up.', startPosition: 'Standing.', movementSequence: 'Squat, kick back, push-up, jump.', cues: ['Exhale on effort'], mistakes: ['Skipping push-up'], primaryMuscles: ['Full body'], secondaryMuscles: ['Core'], category: 'conditioning', equipment: ['bodyweight'], impactLevel: 'high', easierVariantId: 'half-burpee', visualAsset: 'exercises/burpee' },
  { id: 'half-burpee', name: 'Half Burpee', description: 'Burpee without push-up.', instructions: 'Squat, step or jump back to plank, return.', startPosition: 'Standing.', movementSequence: 'Squat, plank, stand or small jump.', cues: ['Core tight in plank'], mistakes: ['Hips sag'], primaryMuscles: ['Full body'], secondaryMuscles: ['Core'], category: 'conditioning', equipment: ['bodyweight'], impactLevel: 'medium', harderVariantId: 'burpee', visualAsset: 'exercises/half-burpee' },
  { id: 'mountain-climber', name: 'Mountain Climber', description: 'Running plank.', instructions: 'Drive knees to chest alternately.', startPosition: 'High plank.', movementSequence: 'Alternate knee drives.', cues: ['Shoulders over wrists'], mistakes: ['Bouncing hips'], primaryMuscles: ['Core'], secondaryMuscles: ['Hip flexors'], category: 'core', equipment: ['bodyweight'], impactLevel: 'medium', visualAsset: 'exercises/mountain-climber' },
  { id: 'plank-hold', name: 'Plank Hold', description: 'Isometric core brace.', instructions: 'Hold rigid plank on forearms or hands.', startPosition: 'Forearm or high plank.', movementSequence: 'Hold without sagging.', cues: ['Squeeze glutes'], mistakes: ['Lower back arch'], primaryMuscles: ['Core'], secondaryMuscles: ['Shoulders'], category: 'core', equipment: ['mat'], impactLevel: 'low', visualAsset: 'exercises/plank-hold' },
  { id: 'side-plank', name: 'Side Plank', description: 'Lateral core stability.', instructions: 'Stack feet, lift hips.', startPosition: 'Side-lying on forearm.', movementSequence: 'Hold hips high.', cues: ['Straight line'], mistakes: ['Hips dropping'], primaryMuscles: ['Obliques'], secondaryMuscles: ['Glutes'], category: 'core', equipment: ['mat'], impactLevel: 'low', visualAsset: 'exercises/side-plank' },
  { id: 'sit-up', name: 'Sit-up', description: 'Trunk flexion.', instructions: 'Feet anchored optional, curl up.', startPosition: 'Supine, knees bent.', movementSequence: 'Curl shoulders to knees.', cues: ['Exhale on rise'], mistakes: ['Pulling neck'], primaryMuscles: ['Abs'], secondaryMuscles: ['Hip flexors'], category: 'core', equipment: ['mat'], impactLevel: 'low', visualAsset: 'exercises/sit-up' },
  { id: 'bicycle-crunch', name: 'Bicycle Crunch', description: 'Rotational crunch.', instructions: 'Elbow to opposite knee.', startPosition: 'Supine, hands behind head.', movementSequence: 'Pedal legs, rotate torso.', cues: ['Slow and controlled'], mistakes: ['Rushing reps'], primaryMuscles: ['Abs'], secondaryMuscles: ['Obliques'], category: 'core', equipment: ['mat'], impactLevel: 'low', visualAsset: 'exercises/bicycle-crunch' },
  { id: 'leg-raise', name: 'Leg Raise', description: 'Lower ab focus.', instructions: 'Raise legs without arching back.', startPosition: 'Supine, legs straight.', movementSequence: 'Lift legs to 90°, lower with control.', cues: ['Press low back down'], mistakes: ['Swinging legs'], primaryMuscles: ['Abs'], secondaryMuscles: ['Hip flexors'], category: 'core', equipment: ['mat'], impactLevel: 'low', visualAsset: 'exercises/leg-raise' },
  { id: 'v-up', name: 'V-up', description: 'Simultaneous trunk and leg lift.', instructions: 'Touch toes at top.', startPosition: 'Supine.', movementSequence: 'Fold body to V, lower controlled.', cues: ['Reach long'], mistakes: ['Bent knees'], primaryMuscles: ['Abs'], secondaryMuscles: ['Hip flexors'], category: 'core', equipment: ['mat'], impactLevel: 'medium', visualAsset: 'exercises/v-up' },
  { id: 'hollow-hold', name: 'Hollow Hold', description: 'Gymnastics hollow position.', instructions: 'Lower back pressed to floor.', startPosition: 'Supine, arms overhead.', movementSequence: 'Lift shoulders and legs, hold.', cues: ['Ribs down'], mistakes: ['Back peeling up'], primaryMuscles: ['Abs'], secondaryMuscles: ['Hip flexors'], category: 'core', equipment: ['mat'], impactLevel: 'low', visualAsset: 'exercises/hollow-hold' },
  { id: 'superman-hold', name: 'Superman Hold', description: 'Posterior chain hold.', instructions: 'Lift arms and legs off floor.', startPosition: 'Prone.', movementSequence: 'Hold lift, breathe.', cues: ['Glutes engaged'], mistakes: ['Hyperextending neck'], primaryMuscles: ['Back'], secondaryMuscles: ['Glutes'], category: 'core', equipment: ['mat'], impactLevel: 'low', visualAsset: 'exercises/superman-hold' },
  { id: 'glute-bridge', name: 'Glute Bridge', description: 'Hip extension from floor.', instructions: 'Drive hips up, squeeze glutes.', startPosition: 'Supine, knees bent.', movementSequence: 'Lift hips, lower with control.', cues: ['Pause at top'], mistakes: ['Overarching'], primaryMuscles: ['Glutes'], secondaryMuscles: ['Hamstrings'], category: 'hinge', equipment: ['mat'], impactLevel: 'low', harderVariantId: 'single-leg-bridge', visualAsset: 'exercises/glute-bridge' },
  { id: 'single-leg-bridge', name: 'Single-leg Bridge', description: 'Unilateral glute bridge.', instructions: 'One foot planted, other extended.', startPosition: 'Glute bridge setup.', movementSequence: 'Bridge on one leg.', cues: ['Level hips'], mistakes: ['Hip drop'], primaryMuscles: ['Glutes'], secondaryMuscles: ['Hamstrings'], category: 'hinge', equipment: ['mat'], impactLevel: 'medium', easierVariantId: 'glute-bridge', visualAsset: 'exercises/single-leg-bridge' },
