import type { WorkoutStructure } from '../domain/types';

export interface ExerciseSeed {
  id: string;
  name: string;
  description: string;
  instructions: string;
  startPosition: string;
  movementSequence: string;
  cues: string[];
  mistakes: string[];
  primaryMuscles: string[];
  secondaryMuscles: string[];
  category: string;
  equipment: string[];
  impactLevel: 'low' | 'medium' | 'high';
  easierVariantId?: string;
  harderVariantId?: string;
  visualAsset: string;
}

export const EXERCISE_SEEDS: ExerciseSeed[] = [
  { id: 'wall-push-up', name: 'Wall Push-up', description: 'Incline push pattern against a wall.', instructions: 'Stand arm\'s length from wall, hands at chest height.', startPosition: 'Stand facing wall, palms flat.', movementSequence: 'Bend elbows to bring chest toward wall, press back.', cues: ['Brace core', 'Elbows at 45°'], mistakes: ['Sagging hips'], primaryMuscles: ['Chest'], secondaryMuscles: ['Triceps', 'Shoulders'], category: 'push', equipment: ['bodyweight'], impactLevel: 'low', harderVariantId: 'knee-push-up', visualAsset: 'exercises/wall-push-up' },
  { id: 'knee-push-up', name: 'Knee Push-up', description: 'Scaled push-up from knees.', instructions: 'Knees down, hands under shoulders.', startPosition: 'High plank from knees.', movementSequence: 'Lower chest between hands, press up.', cues: ['Straight line knee to head'], mistakes: ['Hips piking up'], primaryMuscles: ['Chest'], secondaryMuscles: ['Triceps'], category: 'push', equipment: ['mat'], impactLevel: 'low', easierVariantId: 'wall-push-up', harderVariantId: 'push-up', visualAsset: 'exercises/knee-push-up' },
  { id: 'push-up', name: 'Push-up', description: 'Standard floor push-up.', instructions: 'Hands shoulder-width, full body plank.', startPosition: 'High plank.', movementSequence: 'Lower chest to floor, full extension up.', cues: ['Ribs down', 'Glutes tight'], mistakes: ['Partial range'], primaryMuscles: ['Chest'], secondaryMuscles: ['Triceps', 'Core'], category: 'push', equipment: ['bodyweight'], impactLevel: 'medium', easierVariantId: 'knee-push-up', harderVariantId: 'decline-push-up', visualAsset: 'exercises/push-up' },
  { id: 'decline-push-up', name: 'Decline Push-up', description: 'Feet elevated push-up.', instructions: 'Feet on bench or step.', startPosition: 'Plank with feet elevated.', movementSequence: 'Lower under control, press up.', cues: ['Control descent'], mistakes: ['Bouncing at bottom'], primaryMuscles: ['Chest'], secondaryMuscles: ['Shoulders'], category: 'push', equipment: ['bench'], impactLevel: 'medium', easierVariantId: 'push-up', visualAsset: 'exercises/decline-push-up' },
  { id: 'pike-push-up', name: 'Pike Push-up', description: 'Shoulder-focused push pattern.', instructions: 'Hips high, head travels forward-down.', startPosition: 'Downward dog style pike.', movementSequence: 'Bend elbows, head toward floor, press up.', cues: ['Look between hands'], mistakes: ['Elbows flaring wide'], primaryMuscles: ['Shoulders'], secondaryMuscles: ['Triceps'], category: 'push', equipment: ['bodyweight'], impactLevel: 'medium', visualAsset: 'exercises/pike-push-up' },
  { id: 'diamond-push-up', name: 'Diamond Push-up', description: 'Tricep-biased push-up.', instructions: 'Hands form diamond under chest.', startPosition: 'Plank, hands together.', movementSequence: 'Lower chest to hands, press up.', cues: ['Elbows track back'], mistakes: ['Hands too far forward'], primaryMuscles: ['Triceps'], secondaryMuscles: ['Chest'], category: 'push', equipment: ['bodyweight'], impactLevel: 'medium', easierVariantId: 'push-up', visualAsset: 'exercises/diamond-push-up' },
  { id: 'air-squat', name: 'Air Squat', description: 'Bodyweight squat.', instructions: 'Feet shoulder-width, sit hips back and down.', startPosition: 'Standing tall.', movementSequence: 'Squat to thighs parallel, stand.', cues: ['Knees track toes', 'Chest up'], mistakes: ['Heels lifting'], primaryMuscles: ['Quads'], secondaryMuscles: ['Glutes'], category: 'squat', equipment: ['bodyweight'], impactLevel: 'low', harderVariantId: 'jump-squat', visualAsset: 'exercises/air-squat' },
  { id: 'jump-squat', name: 'Jump Squat', description: 'Explosive squat with jump.', instructions: 'Squat then drive through floor to jump.', startPosition: 'Standing.', movementSequence: 'Squat, explode up, land soft.', cues: ['Soft landing'], mistakes: ['Landing stiff'], primaryMuscles: ['Quads'], secondaryMuscles: ['Glutes', 'Calves'], category: 'squat', equipment: ['bodyweight'], impactLevel: 'high', easierVariantId: 'air-squat', visualAsset: 'exercises/jump-squat' },
  { id: 'walking-lunge', name: 'Walking Lunge', description: 'Alternating forward lunges.', instructions: 'Step long, back knee kisses floor.', startPosition: 'Standing.', movementSequence: 'Lunge right, then left, continue.', cues: ['Torso upright'], mistakes: ['Short steps'], primaryMuscles: ['Quads'], secondaryMuscles: ['Glutes'], category: 'lunge', equipment: ['bodyweight'], impactLevel: 'medium', easierVariantId: 'reverse-lunge', harderVariantId: 'jumping-lunge', visualAsset: 'exercises/walking-lunge' },
  { id: 'reverse-lunge', name: 'Reverse Lunge', description: 'Step back lunge pattern.', instructions: 'Step back, lower, return.', startPosition: 'Standing.', movementSequence: 'Step back into lunge, drive up.', cues: ['Front shin vertical'], mistakes: ['Leaning forward'], primaryMuscles: ['Quads'], secondaryMuscles: ['Glutes'], category: 'lunge', equipment: ['bodyweight'], impactLevel: 'low', harderVariantId: 'walking-lunge', visualAsset: 'exercises/reverse-lunge' },
  { id: 'jumping-lunge', name: 'Jumping Lunge', description: 'Alternating jump lunges.', instructions: 'Switch legs in air.', startPosition: 'Lunge position.', movementSequence: 'Jump and switch, land soft.', cues: ['Absorb landing'], mistakes: ['Knee collapse'], primaryMuscles: ['Quads'], secondaryMuscles: ['Glutes'], category: 'lunge', equipment: ['bodyweight'], impactLevel: 'high', easierVariantId: 'walking-lunge', visualAsset: 'exercises/jumping-lunge' },
  { id: 'burpee', name: 'Burpee', description: 'Full body conditioning move.', instructions: 'Drop to floor, chest down, jump up.', startPosition: 'Standing.', movementSequence: 'Squat, kick back, push-up, jump.', cues: ['Exhale on effort'], mistakes: ['Skipping push-up'], primaryMuscles: ['Full body'], secondaryMuscles: ['Core'], category: 'conditioning', equipment: ['bodyweight'], impactLevel: 'high', easierVariantId: 'half-burpee', visualAsset: 'exercises/burpee' },
  { id: 'half-burpee', name: 'Half Burpee', description: 'Burpee without push-up.', instructions: 'Squat, step or jump back to plank, return.', startPosition: 'Standing.', movementSequence: 'Squat, plank, stand or small jump.', cues: ['Core tight in plank'], mistakes: ['Hips sag'], primaryMuscles: ['Full body'], secondaryMuscles: ['Core'], category: 'conditioning', equipment: ['bodyweight'], impactLevel: 'medium', harderVariantId: 'burpee', visualAsset: 'exercises/half-burpee' },
  { id: 'mountain-climber', name: 'Mountain Climber', description: 'Running plank.', instructions: 'Drive knees to chest alternately.', startPosition: 'High plank.', movementSequence: 'Alternate knee drives.', cues: ['Shoulders over wrists'], mistakes: ['Bouncing hips'], primaryMuscles: ['Core'], secondaryMuscles: ['Hip flexors'], category: 'core', equipment: ['bodyweight'], impactLevel: 'medium', visualAsset: 'exercises/mountain-climber' },
  { id: 'plank-hold', name: 'Plank Hold', description: 'Isometric core brace.', instructions: 'Hold rigid plank on forearms or hands.', startPosition: 'Forearm or high plank.', movementSequence: 'Hold without sagging.', cues: ['Squeeze glutes'], mistakes: ['Lower back arch'], primaryMuscles: ['Core'], secondaryMuscles: ['Shoulders'], category: 'core', equipment: ['mat'], impactLevel: 'low', visualAsset: 'exercises/plank-hold' },
  { id: 'side-plank', name: 'Side Plank', description: 'Lateral core stability.', instructions: 'Stack feet, lift hips.', startPosition: 'Side-lying on forearm.', movementSequence: 'Hold hips high.', cues: ['Straight line'], mistakes: ['Hips dropping'], primaryMuscles: ['Obliques'], secondaryMuscles: ['Glutes'], category: 'core', equipment: ['mat'], impactLevel: 'low', visualAsset: 'exercises/side-plank' },
  { id: 'sit-up', name: 'Sit-up', description: 'Trunk flexion.', instructions: 'Feet anchored optional, curl up.', startPosition: 'Supine, knees bent.', movementSequence: 'Curl shoulders to knees.', cues: ['Exhale on rise'], mistakes: ['Pulling neck'], primaryMuscles: ['Abs'], secondaryMuscles: ['Hip flexors'], category: 'core', equipment: ['mat'], impactLevel: 'low', visualAsset: 'exercises/sit-up' },
  { id: 'bicycle-crunch', name: 'Bicycle Crunch', description: 'Rotational crunch.', instructions: 'Elbow to opposite knee.', startPosition: 'Supine, hands behind head.', movementSequence: 'Pedal legs, rotate torso.', cues: ['Slow and controlled'], mistakes: ['Rushing reps'], primaryMuscles: ['Abs'], secondaryMuscles: ['Obliques'], category: 'core', equipment: ['mat'], impactLevel: 'low', visualAsset: 'exercises/bicycle-crunch' },
  { id: 'leg-raise', name: 'Leg Raise', description: 'Lower ab focus.', instructions: 'Raise legs without arching back.', startPosition: 'Supine, legs straight.', movementSequence: 'Lift legs to 90°, lower with control.', cues: ['Press low back down'], mistakes: ['Swinging legs'], primaryMuscles: ['Abs'], secondaryMuscles: ['Hip flexors'], category: 'core', equipment: ['mat'], impactLevel: 'low', visualAsset: 'exercises/leg-raise' },
  { id: 'v-up', name: 'V-up', description: 'Simultaneous trunk and leg lift.', instructions: 'Touch toes at top.', startPosition: 'Supine.', movementSequence: 'Fold body to V, lower controlled.', cues: ['Reach long'], mistakes: ['Bent knees'], primaryMuscles: ['Abs'], secondaryMuscles: ['Hip flexors'], category: 'core', equipment: ['mat'], impactLevel: 'medium', visualAsset: 'exercises/v-up' },
  { id: 'hollow-hold', name: 'Hollow Hold', description: 'Gymnastics hollow position.', instructions: 'Lower back pressed to floor.', startPosition: 'Supine, arms overhead.', movementSequence: 'Lift shoulders and legs, hold.', cues: ['Ribs down'], mistakes: ['Back peeling up'], primaryMuscles: ['Abs'], secondaryMuscles: ['Hip flexors'], category: 'core', equipment: ['mat'], impactLevel: 'low', visualAsset: 'exercises/hollow-hold' },
  { id: 'superman-hold', name: 'Superman Hold', description: 'Posterior chain hold.', instructions: 'Lift arms and legs off floor.', startPosition: 'Prone.', movementSequence: 'Hold lift, breathe.', cues: ['Glutes engaged'], mistakes: ['Hyperextending neck'], primaryMuscles: ['Back'], secondaryMuscles: ['Glutes'], category: 'core', equipment: ['mat'], impactLevel: 'low', visualAsset: 'exercises/superman-hold' },
  { id: 'glute-bridge', name: 'Glute Bridge', description: 'Hip extension from floor.', instructions: 'Drive hips up, squeeze glutes.', startPosition: 'Supine, knees bent.', movementSequence: 'Lift hips, lower with control.', cues: ['Pause at top'], mistakes: ['Overarching'], primaryMuscles: ['Glutes'], secondaryMuscles: ['Hamstrings'], category: 'hinge', equipment: ['mat'], impactLevel: 'low', harderVariantId: 'single-leg-bridge', visualAsset: 'exercises/glute-bridge' },
  { id: 'single-leg-bridge', name: 'Single-leg Bridge', description: 'Unilateral glute bridge.', instructions: 'One foot planted, other extended.', startPosition: 'Glute bridge setup.', movementSequence: 'Bridge on one leg.', cues: ['Level hips'], mistakes: ['Hip drop'], primaryMuscles: ['Glutes'], secondaryMuscles: ['Hamstrings'], category: 'hinge', equipment: ['mat'], impactLevel: 'medium', easierVariantId: 'glute-bridge', visualAsset: 'exercises/single-leg-bridge' },
  { id: 'high-knees', name: 'High Knees', description: 'Running in place, knees high.', instructions: 'Drive knees to hip height.', startPosition: 'Standing.', movementSequence: 'Fast alternating knee drives.', cues: ['Pump arms'], mistakes: ['Leaning back'], primaryMuscles: ['Cardio'], secondaryMuscles: ['Hip flexors'], category: 'cardio', equipment: ['bodyweight'], impactLevel: 'medium', visualAsset: 'exercises/high-knees' },
  { id: 'butt-kicks', name: 'Butt Kicks', description: 'Heels to glutes jog.', instructions: 'Quick feet, kick heels back.', startPosition: 'Standing.', movementSequence: 'Jog kicking heels up.', cues: ['Upright torso'], mistakes: ['Kicking too far back'], primaryMuscles: ['Cardio'], secondaryMuscles: ['Hamstrings'], category: 'cardio', equipment: ['bodyweight'], impactLevel: 'medium', visualAsset: 'exercises/butt-kicks' },
  { id: 'jumping-jack', name: 'Jumping Jack', description: 'Classic cardio opener.', instructions: 'Jump feet wide, arms overhead.', startPosition: 'Standing.', movementSequence: 'Jump in/out with arm swing.', cues: ['Soft landings'], mistakes: ['Stiff knees'], primaryMuscles: ['Cardio'], secondaryMuscles: ['Calves'], category: 'cardio', equipment: ['bodyweight'], impactLevel: 'medium', visualAsset: 'exercises/jumping-jack' },
  { id: 'seal-jack', name: 'Seal Jack', description: 'Jumping jack with forward clap.', instructions: 'Clap hands in front as feet jump wide.', startPosition: 'Standing.', movementSequence: 'Jump wide, clap, return.', cues: ['Stay light on feet'], mistakes: ['Arms only'], primaryMuscles: ['Cardio'], secondaryMuscles: ['Shoulders'], category: 'cardio', equipment: ['bodyweight'], impactLevel: 'medium', visualAsset: 'exercises/seal-jack' },
  { id: 'skater-hop', name: 'Skater Hop', description: 'Lateral bound cardio.', instructions: 'Leap side to side, land on one foot.', startPosition: 'Standing.', movementSequence: 'Bound laterally, soft land.', cues: ['Bend landing knee'], mistakes: ['Short bounds'], primaryMuscles: ['Cardio'], secondaryMuscles: ['Glutes'], category: 'cardio', equipment: ['bodyweight'], impactLevel: 'high', visualAsset: 'exercises/skater-hop' },
  { id: 'step-up', name: 'Step-up', description: 'Single step onto box or bench.', instructions: 'Drive through whole foot.', startPosition: 'Facing step.', movementSequence: 'Step up, stand tall, step down.', cues: ['Knee tracks over foot'], mistakes: ['Pushing off back foot'], primaryMuscles: ['Quads'], secondaryMuscles: ['Glutes'], category: 'squat', equipment: ['bench'], impactLevel: 'medium', visualAsset: 'exercises/step-up' },
  { id: 'calf-raise', name: 'Calf Raise', description: 'Heel raise for calves.', instructions: 'Rise onto toes, lower slow.', startPosition: 'Standing.', movementSequence: 'Lift heels, lower with control.', cues: ['Full range'], mistakes: ['Bouncing'], primaryMuscles: ['Calves'], secondaryMuscles: [], category: 'accessory', equipment: ['bodyweight'], impactLevel: 'low', visualAsset: 'exercises/calf-raise' },
  { id: 'tricep-dip', name: 'Tricep Dip', description: 'Chair or bench dip.', instructions: 'Lower until elbows ~90°.', startPosition: 'Hands on bench behind you.', movementSequence: 'Lower hips, press up.', cues: ['Shoulders down'], mistakes: ['Shrugging shoulders'], primaryMuscles: ['Triceps'], secondaryMuscles: ['Chest'], category: 'push', equipment: ['bench'], impactLevel: 'medium', visualAsset: 'exercises/tricep-dip' },
  { id: 'bear-crawl', name: 'Bear Crawl', description: 'Quadruped locomotion.', instructions: 'Knees hover, move opposite hand/foot.', startPosition: 'All fours, knees up.', movementSequence: 'Crawl forward or in place.', cues: ['Quiet hips'], mistakes: ['Hips swaying'], primaryMuscles: ['Core'], secondaryMuscles: ['Shoulders'], category: 'conditioning', equipment: ['bodyweight'], impactLevel: 'medium', visualAsset: 'exercises/bear-crawl' },
  { id: 'crab-walk', name: 'Crab Walk', description: 'Reverse tabletop walk.', instructions: 'Hips up, walk on hands and feet.', startPosition: 'Crab position.', movementSequence: 'Walk forward/back.', cues: ['Chest open'], mistakes: ['Hips dropping'], primaryMuscles: ['Triceps'], secondaryMuscles: ['Glutes'], category: 'conditioning', equipment: ['bodyweight'], impactLevel: 'medium', visualAsset: 'exercises/crab-walk' },
  { id: 'inchworm', name: 'Inchworm', description: 'Walk out to plank and back.', instructions: 'Hands walk out, walk feet to hands.', startPosition: 'Standing.', movementSequence: 'Fold, walk to plank, walk feet in.', cues: ['Legs straight if possible'], mistakes: ['Bent knees throughout'], primaryMuscles: ['Core'], secondaryMuscles: ['Hamstrings'], category: 'conditioning', equipment: ['bodyweight'], impactLevel: 'low', visualAsset: 'exercises/inchworm' },
  { id: 'broad-jump', name: 'Broad Jump', description: 'Horizontal jump for power.', instructions: 'Swing arms, jump far, stick landing.', startPosition: 'Standing.', movementSequence: 'Countermovement jump forward.', cues: ['Land balanced'], mistakes: ['Falling forward'], primaryMuscles: ['Power'], secondaryMuscles: ['Quads'], category: 'conditioning', equipment: ['bodyweight'], impactLevel: 'high', visualAsset: 'exercises/broad-jump' },
  { id: 'squat-hold', name: 'Squat Hold', description: 'Isometric squat position.', instructions: 'Hold bottom of squat.', startPosition: 'Squat depth.', movementSequence: 'Hold without rising.', cues: ['Weight in heels'], mistakes: ['Rising too high'], primaryMuscles: ['Quads'], secondaryMuscles: ['Glutes'], category: 'squat', equipment: ['bodyweight'], impactLevel: 'low', visualAsset: 'exercises/squat-hold' },
  { id: 'wall-sit', name: 'Wall Sit', description: 'Back against wall, thighs parallel.', instructions: 'Slide down, hold seated angle.', startPosition: 'Back on wall.', movementSequence: 'Hold 90° knee bend.', cues: ['Knees over ankles'], mistakes: ['Hands on thighs'], primaryMuscles: ['Quads'], secondaryMuscles: ['Glutes'], category: 'squat', equipment: ['bodyweight'], impactLevel: 'low', visualAsset: 'exercises/wall-sit' },
  { id: 'flutter-kick', name: 'Flutter Kick', description: 'Small alternating leg kicks.', instructions: 'Low back down, kick small.', startPosition: 'Supine, hands under hips.', movementSequence: 'Alternate small kicks.', cues: ['Belly tight'], mistakes: ['Large kicks'], primaryMuscles: ['Abs'], secondaryMuscles: ['Hip flexors'], category: 'core', equipment: ['mat'], impactLevel: 'low', visualAsset: 'exercises/flutter-kick' },
  { id: 'russian-twist', name: 'Russian Twist', description: 'Seated rotation.', instructions: 'Rotate torso side to side.', startPosition: 'Seated, feet lifted optional.', movementSequence: 'Twist left and right.', cues: ['Rotate from ribs'], mistakes: ['Only moving arms'], primaryMuscles: ['Obliques'], secondaryMuscles: ['Abs'], category: 'core', equipment: ['mat'], impactLevel: 'low', visualAsset: 'exercises/russian-twist' },
  { id: 'dead-bug', name: 'Dead Bug', description: 'Anti-extension core drill.', instructions: 'Opposite arm/leg extend.', startPosition: 'Supine, table top legs.', movementSequence: 'Extend opposite limbs, return.', cues: ['Back flat'], mistakes: ['Back arching'], primaryMuscles: ['Core'], secondaryMuscles: [], category: 'core', equipment: ['mat'], impactLevel: 'low', visualAsset: 'exercises/dead-bug' },
  { id: 'bird-dog', name: 'Bird Dog', description: 'Quadruped reach.', instructions: 'Extend opposite arm and leg.', startPosition: 'All fours.', movementSequence: 'Reach long, return, switch.', cues: ['Hips square'], mistakes: ['Rotating hips'], primaryMuscles: ['Core'], secondaryMuscles: ['Glutes'], category: 'core', equipment: ['mat'], impactLevel: 'low', visualAsset: 'exercises/bird-dog' },
  { id: 'plank-jack', name: 'Plank Jack', description: 'Jump feet in/out in plank.', instructions: 'Maintain plank while feet jump.', startPosition: 'High plank.', movementSequence: 'Jump feet wide/narrow.', cues: ['Hips stable'], mistakes: ['Bouncing hips'], primaryMuscles: ['Core'], secondaryMuscles: ['Cardio'], category: 'conditioning', equipment: ['bodyweight'], impactLevel: 'medium', visualAsset: 'exercises/plank-jack' },
  { id: 'sprawl', name: 'Sprawl', description: 'Burpee without push-up or jump.', instructions: 'Drop hips to plank fast, snap up.', startPosition: 'Standing.', movementSequence: 'Hands down, jump back, return.', cues: ['Hips low'], mistakes: ['Slow feet'], primaryMuscles: ['Conditioning'], secondaryMuscles: ['Core'], category: 'conditioning', equipment: ['bodyweight'], impactLevel: 'medium', visualAsset: 'exercises/sprawl' },
  { id: 'squat-thrust', name: 'Squat Thrust', description: 'Plank kick-back from squat.', instructions: 'Hands down, jump feet to plank.', startPosition: 'Standing.', movementSequence: 'Squat, thrust back, return.', cues: ['Core tight'], mistakes: ['Hips high in plank'], primaryMuscles: ['Conditioning'], secondaryMuscles: ['Core'], category: 'conditioning', equipment: ['bodyweight'], impactLevel: 'medium', visualAsset: 'exercises/squat-thrust' },
  { id: 'plank-to-push-up', name: 'Plank to Push-up', description: 'Alternate elbow to hand.', instructions: 'Press up one arm at a time.', startPosition: 'Forearm plank.', movementSequence: 'Press to hands, lower to elbows.', cues: ['Minimize hip sway'], mistakes: ['Rocking hips'], primaryMuscles: ['Core'], secondaryMuscles: ['Triceps'], category: 'core', equipment: ['bodyweight'], impactLevel: 'medium', visualAsset: 'exercises/plank-to-push-up' },
  { id: 'side-shuffle', name: 'Side Shuffle', description: 'Lateral quick feet.', instructions: 'Athletic stance, shuffle without crossing feet.', startPosition: 'Quarter squat.', movementSequence: 'Shuffle left/right.', cues: ['Stay low'], mistakes: ['Crossing feet'], primaryMuscles: ['Cardio'], secondaryMuscles: ['Glutes'], category: 'cardio', equipment: ['bodyweight'], impactLevel: 'medium', visualAsset: 'exercises/side-shuffle' },
  { id: 'jump-rope', name: 'Jump Rope', description: 'Rope or mimic rope jumps.', instructions: 'Small hops on balls of feet.', startPosition: 'Standing with rope or mimic.', movementSequence: 'Rhythmic jumps.', cues: ['Elbows in'], mistakes: ['High jumps'], primaryMuscles: ['Cardio'], secondaryMuscles: ['Calves'], category: 'cardio', equipment: ['jump-rope'], impactLevel: 'medium', visualAsset: 'exercises/jump-rope' },
  { id: 'shoulder-tap', name: 'Shoulder Tap', description: 'Plank shoulder taps.', instructions: 'Tap opposite shoulder in plank.', startPosition: 'High plank.', movementSequence: 'Alternate taps with minimal sway.', cues: ['Feet wide for stability'], mistakes: ['Hip rotation'], primaryMuscles: ['Core'], secondaryMuscles: ['Shoulders'], category: 'core', equipment: ['bodyweight'], impactLevel: 'low', visualAsset: 'exercises/shoulder-tap' },
  { id: 'single-leg-deadlift', name: 'Single-leg Deadlift', description: 'Hip hinge on one leg.', instructions: 'Hinge forward, back leg extends.', startPosition: 'Standing one leg.', movementSequence: 'Hinge, return to stand.', cues: ['Hips square'], mistakes: ['Rotating hips'], primaryMuscles: ['Hamstrings'], secondaryMuscles: ['Glutes'], category: 'hinge', equipment: ['bodyweight'], impactLevel: 'low', visualAsset: 'exercises/single-leg-deadlift' },
  { id: 'cossack-squat', name: 'Cossack Squat', description: 'Lateral squat shift.', instructions: 'Shift weight side to side in wide stance.', startPosition: 'Wide stance.', movementSequence: 'Squat to one side, alternate.', cues: ['Heel down if possible'], mistakes: ['Collapsing chest'], primaryMuscles: ['Quads'], secondaryMuscles: ['Glutes'], category: 'squat', equipment: ['bodyweight'], impactLevel: 'medium', visualAsset: 'exercises/cossack-squat' },
  { id: 'box-breather', name: 'Box Breather', description: 'Recovery breathing pattern.', instructions: '4-count inhale, hold, exhale, hold.', startPosition: 'Seated or standing.', movementSequence: 'Controlled breathing cycle.', cues: ['Nasal inhale if possible'], mistakes: ['Shallow breaths'], primaryMuscles: ['Recovery'], secondaryMuscles: [], category: 'recovery', equipment: ['bodyweight'], impactLevel: 'low', visualAsset: 'exercises/box-breather' },
];

export interface WorkoutSeed {
  id: string;
  slug: string;
  name: string;
  symbol: string;
  focus: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced' | 'elite';
  estimatedMinutesMin: number;
  estimatedMinutesMax: number;
  equipment: string[];
  format: WorkoutStructure['format'];
  identityColor: string;
  progressionTier: string;
  structure: WorkoutStructure;
}

function rounds(count: number, steps: WorkoutStructure['rounds'][0]['steps']): WorkoutStructure {
  return {
    format: 'fixed_rounds',
    rounds: Array.from({ length: count }, (_, i) => ({ roundNumber: i + 1, steps })),
  };
}

export const WORKOUT_SEEDS: WorkoutSeed[] = [
  { id: 'w-tempest', slug: 'tempest', name: 'TEMPEST', symbol: '⛈', focus: 'full_body', difficulty: 'advanced', estimatedMinutesMin: 12, estimatedMinutesMax: 18, equipment: ['bodyweight'], format: 'fixed_rounds', identityColor: '#4ECDC4', progressionTier: 'standard', structure: rounds(5, [{ exerciseId: 'air-squat', reps: 20 }, { exerciseId: 'push-up', reps: 15 }, { exerciseId: 'burpee', reps: 10 }]) },
  { id: 'w-ember', slug: 'ember', name: 'EMBER', symbol: '🔥', focus: 'core', difficulty: 'intermediate', estimatedMinutesMin: 10, estimatedMinutesMax: 14, equipment: ['mat'], format: 'fixed_rounds', identityColor: '#F4A261', progressionTier: 'foundation', structure: rounds(4, [{ exerciseId: 'walking-lunge', reps: 12 }, { exerciseId: 'sit-up', reps: 12 }, { exerciseId: 'plank-hold', durationSec: 30 }]) },
  { id: 'w-riptide', slug: 'riptide', name: 'RIPTIDE', symbol: '🌊', focus: 'cardio', difficulty: 'intermediate', estimatedMinutesMin: 14, estimatedMinutesMax: 20, equipment: ['bodyweight'], format: 'chipper', identityColor: '#5B8DEF', progressionTier: 'standard', structure: { format: 'chipper', rounds: [{ roundNumber: 1, steps: [{ exerciseId: 'jumping-jack', reps: 50 }, { exerciseId: 'air-squat', reps: 40 }, { exerciseId: 'mountain-climber', reps: 30 }, { exerciseId: 'push-up', reps: 20 }, { exerciseId: 'burpee', reps: 10 }] }] } },
  { id: 'w-avalanche', slug: 'avalanche', name: 'AVALANCHE', symbol: '🏔', focus: 'lower', difficulty: 'advanced', estimatedMinutesMin: 14, estimatedMinutesMax: 20, equipment: ['bodyweight'], format: 'fixed_rounds', identityColor: '#E8ECF4', progressionTier: 'advanced', structure: rounds(5, [{ exerciseId: 'air-squat', reps: 25 }, { exerciseId: 'walking-lunge', reps: 20 }, { exerciseId: 'jump-squat', reps: 15 }]) },
  { id: 'w-summit', slug: 'summit', name: 'SUMMIT', symbol: '△', focus: 'full_body', difficulty: 'elite', estimatedMinutesMin: 15, estimatedMinutesMax: 25, equipment: ['bodyweight'], format: 'ladder', identityColor: '#C9B1FF', progressionTier: 'elite', structure: { format: 'ladder', rounds: Array.from({ length: 10 }, (_, i) => ({ roundNumber: i + 1, steps: [{ exerciseId: 'burpee', reps: i + 1 }, { exerciseId: 'air-squat', reps: 10 }] })) } },
  { id: 'w-drift', slug: 'drift', name: 'DRIFT', symbol: '〰', focus: 'cardio', difficulty: 'beginner', estimatedMinutesMin: 8, estimatedMinutesMax: 12, equipment: ['bodyweight'], format: 'intervals', identityColor: '#7DD3FC', progressionTier: 'foundation', structure: { format: 'intervals', intervalWorkSec: 45, intervalRestSec: 15, intervalRounds: 8, rounds: [{ roundNumber: 1, steps: [{ exerciseId: 'high-knees', durationSec: 45 }, { exerciseId: 'jumping-jack', durationSec: 45 }, { exerciseId: 'butt-kicks', durationSec: 45 }, { exerciseId: 'mountain-climber', durationSec: 45 }] }] } },
  { id: 'w-flare', slug: 'flare', name: 'FLARE', symbol: '☀', focus: 'upper', difficulty: 'intermediate', estimatedMinutesMin: 12, estimatedMinutesMax: 16, equipment: ['bench'], format: 'fixed_rounds', identityColor: '#FFD166', progressionTier: 'standard', structure: rounds(4, [{ exerciseId: 'pike-push-up', reps: 15 }, { exerciseId: 'tricep-dip', reps: 20 }, { exerciseId: 'shoulder-tap', reps: 24 }]) },
  { id: 'w-cascade', slug: 'cascade', name: 'CASCADE', symbol: '▽', focus: 'lower', difficulty: 'intermediate', estimatedMinutesMin: 12, estimatedMinutesMax: 18, equipment: ['bodyweight'], format: 'chipper', identityColor: '#6BCB77', progressionTier: 'standard', structure: { format: 'chipper', rounds: [{ roundNumber: 1, steps: [{ exerciseId: 'single-leg-deadlift', reps: 30 }, { exerciseId: 'reverse-lunge', reps: 24 }, { exerciseId: 'air-squat', reps: 18 }, { exerciseId: 'calf-raise', reps: 12 }, { exerciseId: 'jump-squat', reps: 6 }] }] } },
  { id: 'w-gale', slug: 'gale', name: 'GALE', symbol: '💨', focus: 'conditioning', difficulty: 'advanced', estimatedMinutesMin: 18, estimatedMinutesMax: 25, equipment: ['bodyweight'], format: 'amrap', identityColor: '#94A3B8', progressionTier: 'advanced', structure: { format: 'amrap', timeCapSec: 1200, rounds: [{ roundNumber: 1, steps: [{ exerciseId: 'burpee', reps: 5 }, { exerciseId: 'air-squat', reps: 10 }, { exerciseId: 'jumping-jack', reps: 15 }] }] } },
  { id: 'w-frost', slug: 'frost', name: 'FROST', symbol: '❄', focus: 'core', difficulty: 'intermediate', estimatedMinutesMin: 10, estimatedMinutesMax: 14, equipment: ['mat'], format: 'fixed_rounds', identityColor: '#BAE6FD', progressionTier: 'foundation', structure: rounds(5, [{ exerciseId: 'plank-hold', durationSec: 45 }, { exerciseId: 'bicycle-crunch', reps: 20 }, { exerciseId: 'leg-raise', reps: 15 }]) },
  { id: 'w-ridge', slug: 'ridge', name: 'RIDGE', symbol: '⛰', focus: 'full_body', difficulty: 'beginner', estimatedMinutesMin: 8, estimatedMinutesMax: 12, equipment: ['bodyweight'], format: 'fixed_rounds', identityColor: '#A3E635', progressionTier: 'foundation', structure: rounds(3, [{ exerciseId: 'air-squat', reps: 15 }, { exerciseId: 'knee-push-up', reps: 10 }, { exerciseId: 'half-burpee', reps: 8 }]) },
  { id: 'w-surge', slug: 'surge', name: 'SURGE', symbol: '⚡', focus: 'cardio', difficulty: 'advanced', estimatedMinutesMin: 10, estimatedMinutesMax: 15, equipment: ['bodyweight'], format: 'intervals', identityColor: '#FDE047', progressionTier: 'advanced', structure: { format: 'intervals', intervalWorkSec: 40, intervalRestSec: 20, intervalRounds: 10, rounds: [{ roundNumber: 1, steps: [{ exerciseId: 'burpee', durationSec: 40 }, { exerciseId: 'skater-hop', durationSec: 40 }, { exerciseId: 'mountain-climber', durationSec: 40 }] }] } },
  { id: 'w-horizon', slug: 'horizon', name: 'HORIZON', symbol: '◐', focus: 'mixed', difficulty: 'intermediate', estimatedMinutesMin: 14, estimatedMinutesMax: 20, equipment: ['bodyweight'], format: 'fixed_rounds', identityColor: '#FB7185', progressionTier: 'standard', structure: rounds(4, [{ exerciseId: 'inchworm', reps: 8 }, { exerciseId: 'push-up', reps: 12 }, { exerciseId: 'walking-lunge', reps: 16 }, { exerciseId: 'sprawl', reps: 10 }]) },
  { id: 'w-quake', slug: 'quake', name: 'QUAKE', symbol: '◎', focus: 'lower', difficulty: 'elite', estimatedMinutesMin: 16, estimatedMinutesMax: 22, equipment: ['bodyweight'], format: 'fixed_rounds', identityColor: '#F97316', progressionTier: 'elite', structure: rounds(6, [{ exerciseId: 'jump-squat', reps: 20 }, { exerciseId: 'jumping-lunge', reps: 16 }, { exerciseId: 'broad-jump', reps: 8 }]) },
  { id: 'w-mirage', slug: 'mirage', name: 'MIRAGE', symbol: '◈', focus: 'core', difficulty: 'beginner', estimatedMinutesMin: 6, estimatedMinutesMax: 10, equipment: ['mat'], format: 'fixed_rounds', identityColor: '#C4B5FD', progressionTier: 'foundation', structure: rounds(3, [{ exerciseId: 'dead-bug', reps: 10 }, { exerciseId: 'bird-dog', reps: 10 }, { exerciseId: 'glute-bridge', reps: 15 }]) },
  { id: 'w-vortex', slug: 'vortex', name: 'VORTEX', symbol: '🌀', focus: 'conditioning', difficulty: 'intermediate', estimatedMinutesMin: 12, estimatedMinutesMax: 16, equipment: ['bodyweight'], format: 'fixed_rounds', identityColor: '#38BDF8', progressionTier: 'standard', structure: rounds(5, [{ exerciseId: 'squat-thrust', reps: 12 }, { exerciseId: 'push-up', reps: 10 }, { exerciseId: 'high-knees', durationSec: 30 }]) },
  { id: 'w-eclipse', slug: 'eclipse', name: 'ECLIPSE', symbol: '◉', focus: 'upper', difficulty: 'advanced', estimatedMinutesMin: 12, estimatedMinutesMax: 18, equipment: ['bodyweight'], format: 'fixed_rounds', identityColor: '#6366F1', progressionTier: 'advanced', structure: rounds(5, [{ exerciseId: 'push-up', reps: 20 }, { exerciseId: 'diamond-push-up', reps: 10 }, { exerciseId: 'pike-push-up', reps: 12 }]) },
  { id: 'w-dune', slug: 'dune', name: 'DUNE', symbol: '⌒', focus: 'lower', difficulty: 'beginner', estimatedMinutesMin: 8, estimatedMinutesMax: 12, equipment: ['bodyweight'], format: 'fixed_rounds', identityColor: '#EAB308', progressionTier: 'foundation', structure: rounds(4, [{ exerciseId: 'air-squat', reps: 20 }, { exerciseId: 'reverse-lunge', reps: 12 }, { exerciseId: 'wall-sit', durationSec: 30 }]) },
  { id: 'w-current', slug: 'current', name: 'CURRENT', symbol: '⟿', focus: 'cardio', difficulty: 'intermediate', estimatedMinutesMin: 10, estimatedMinutesMax: 14, equipment: ['jump-rope'], format: 'intervals', identityColor: '#22D3EE', progressionTier: 'standard', structure: { format: 'intervals', intervalWorkSec: 50, intervalRestSec: 10, intervalRounds: 8, rounds: [{ roundNumber: 1, steps: [{ exerciseId: 'jump-rope', durationSec: 50 }, { exerciseId: 'jumping-jack', durationSec: 50 }] }] } },
  { id: 'w-apex', slug: 'apex', name: 'APEX', symbol: '▲', focus: 'full_body', difficulty: 'elite', estimatedMinutesMin: 20, estimatedMinutesMax: 30, equipment: ['bodyweight'], format: 'chipper', identityColor: '#EF4444', progressionTier: 'elite', structure: { format: 'chipper', rounds: [{ roundNumber: 1, steps: [{ exerciseId: 'burpee', reps: 40 }, { exerciseId: 'push-up', reps: 40 }, { exerciseId: 'air-squat', reps: 40 }, { exerciseId: 'walking-lunge', reps: 40 }] }] } },
  { id: 'w-zenith', slug: 'zenith', name: 'ZENITH', symbol: '✦', focus: 'mixed', difficulty: 'advanced', estimatedMinutesMin: 15, estimatedMinutesMax: 22, equipment: ['bench'], format: 'fixed_rounds', identityColor: '#A78BFA', progressionTier: 'advanced', structure: rounds(5, [{ exerciseId: 'step-up', reps: 16 }, { exerciseId: 'tricep-dip', reps: 15 }, { exerciseId: 'bear-crawl', durationSec: 30 }]) },
  { id: 'w-rust', slug: 'rust', name: 'RUST', symbol: '⊛', focus: 'strength_endurance', difficulty: 'intermediate', estimatedMinutesMin: 12, estimatedMinutesMax: 16, equipment: ['bodyweight'], format: 'fixed_rounds', identityColor: '#B45309', progressionTier: 'standard', structure: rounds(4, [{ exerciseId: 'squat-hold', durationSec: 45 }, { exerciseId: 'push-up', reps: 15 }, { exerciseId: 'plank-hold', durationSec: 45 }]) },
  { id: 'w-nova', slug: 'nova', name: 'NOVA', symbol: '✹', focus: 'explosive', difficulty: 'advanced', estimatedMinutesMin: 10, estimatedMinutesMax: 14, equipment: ['bodyweight'], format: 'fixed_rounds', identityColor: '#F472B6', progressionTier: 'advanced', structure: rounds(4, [{ exerciseId: 'jump-squat', reps: 15 }, { exerciseId: 'broad-jump', reps: 6 }, { exerciseId: 'burpee', reps: 8 }]) },
  { id: 'w-shoal', slug: 'shoal', name: 'SHOAL', symbol: '≋', focus: 'low_impact', difficulty: 'beginner', estimatedMinutesMin: 8, estimatedMinutesMax: 12, equipment: ['mat'], format: 'fixed_rounds', identityColor: '#2DD4BF', progressionTier: 'foundation', structure: rounds(3, [{ exerciseId: 'wall-push-up', reps: 12 }, { exerciseId: 'glute-bridge', reps: 15 }, { exerciseId: 'bird-dog', reps: 10 }]) },
  { id: 'w-cinder', slug: 'cinder', name: 'CINDER', symbol: '▪', focus: 'core', difficulty: 'advanced', estimatedMinutesMin: 12, estimatedMinutesMax: 16, equipment: ['mat'], format: 'fixed_rounds', identityColor: '#78716C', progressionTier: 'advanced', structure: rounds(5, [{ exerciseId: 'hollow-hold', durationSec: 30 }, { exerciseId: 'v-up', reps: 12 }, { exerciseId: 'russian-twist', reps: 20 }]) },
  { id: 'w-stratus', slug: 'stratus', name: 'STRATUS', symbol: '☁', focus: 'mixed', difficulty: 'intermediate', estimatedMinutesMin: 14, estimatedMinutesMax: 18, equipment: ['bodyweight'], format: 'fixed_rounds', identityColor: '#CBD5E1', progressionTier: 'standard', structure: rounds(4, [{ exerciseId: 'plank-jack', reps: 20 }, { exerciseId: 'air-squat', reps: 20 }, { exerciseId: 'shoulder-tap', reps: 20 }]) },
  { id: 'w-bastion', slug: 'bastion', name: 'BASTION', symbol: '⬡', focus: 'strength_endurance', difficulty: 'elite', estimatedMinutesMin: 18, estimatedMinutesMax: 25, equipment: ['bodyweight'], format: 'fixed_rounds', identityColor: '#64748B', progressionTier: 'elite', structure: rounds(6, [{ exerciseId: 'decline-push-up', reps: 12 }, { exerciseId: 'cossack-squat', reps: 12 }, { exerciseId: 'plank-to-push-up', reps: 16 }]) },
  { id: 'w-pulse', slug: 'pulse', name: 'PULSE', symbol: '♥', focus: 'cardio', difficulty: 'beginner', estimatedMinutesMin: 5, estimatedMinutesMax: 8, equipment: ['bodyweight'], format: 'intervals', identityColor: '#FB923C', progressionTier: 'foundation', structure: { format: 'intervals', intervalWorkSec: 30, intervalRestSec: 15, intervalRounds: 6, rounds: [{ roundNumber: 1, steps: [{ exerciseId: 'marching-high-knees', durationSec: 30 }] }] } },
  { id: 'w-onyx', slug: 'onyx', name: 'ONYX', symbol: '◼', focus: 'full_body', difficulty: 'intermediate', estimatedMinutesMin: 12, estimatedMinutesMax: 18, equipment: ['bodyweight'], format: 'fixed_rounds', identityColor: '#1E293B', progressionTier: 'standard', structure: rounds(4, [{ exerciseId: 'crab-walk', durationSec: 30 }, { exerciseId: 'push-up', reps: 12 }, { exerciseId: 'walking-lunge', reps: 12 }]) },
  { id: 'w-aurora', slug: 'aurora', name: 'AURORA', symbol: '⌇', focus: 'mixed', difficulty: 'intermediate', estimatedMinutesMin: 16, estimatedMinutesMax: 22, equipment: ['mat'], format: 'fixed_rounds', identityColor: '#86EFAC', progressionTier: 'standard', structure: rounds(5, [{ exerciseId: 'single-leg-deadlift', reps: 10 }, { exerciseId: 'push-up', reps: 10 }, { exerciseId: 'side-plank', durationSec: 30 }]) },
