import type { WorkoutExerciseStep, WorkoutStructure } from '../domain/types';
import type { WorkoutSeed } from './types';

// ---------------------------------------------------------------------------
// Structure builders
// ---------------------------------------------------------------------------

type Step = WorkoutExerciseStep;

const rep = (exerciseId: string, reps: number): Step => ({ exerciseId, reps });
const hold = (exerciseId: string, durationSec: number): Step => ({ exerciseId, durationSec });

/** Same steps every round, scored for time. */
function rounds(count: number, steps: Step[], restBetweenRoundsSec?: number): WorkoutStructure {
  const structure: WorkoutStructure = {
    format: 'fixed_rounds',
    rounds: Array.from({ length: count }, (_, i) => ({ roundNumber: i + 1, steps: steps.map((s) => ({ ...s })) })),
  };
  if (restBetweenRoundsSec) structure.restBetweenRoundsSec = restBetweenRoundsSec;
  return structure;
}

/** One pass through a long list, for time. */
function chipper(steps: Step[]): WorkoutStructure {
  return { format: 'chipper', rounds: [{ roundNumber: 1, steps }] };
}

/** Rungs whose reps change with the rung number (1-based), for time. */
function ladder(rungs: number, stepsFor: (rung: number) => Step[]): WorkoutStructure {
  return { format: 'ladder', rounds: Array.from({ length: rungs }, (_, i) => ({ roundNumber: i + 1, steps: stepsFor(i + 1) })) };
}

/** As many rounds as possible of one round, scored by reps. */
function amrap(minutes: number, steps: Step[]): WorkoutStructure {
  return { format: 'amrap', timeCapSec: minutes * 60, rounds: [{ roundNumber: 1, steps }] };
}

/** Every minute on the minute; templates are cycled minute by minute. */
function emom(minutes: number, templates: Step[][]): WorkoutStructure {
  return {
    format: 'emom',
    intervalRounds: minutes,
    intervalWorkSec: 60,
    rounds: templates.map((steps, i) => ({ roundNumber: i + 1, steps })),
  };
}

/** `count` work intervals cycling through the exercises; the athlete counts max reps. */
function intervals(workSec: number, restSec: number, count: number, exerciseIds: string[]): WorkoutStructure {
  return {
    format: 'intervals',
    intervalWorkSec: workSec,
    intervalRestSec: restSec,
    intervalRounds: count,
    rounds: [{ roundNumber: 1, steps: exerciseIds.map((id) => hold(id, workSec)) }],
  };
}

// ---------------------------------------------------------------------------
// Workouts
// ---------------------------------------------------------------------------

export const WORKOUT_SEEDS: WorkoutSeed[] = [
  // Original benchmarks. Their structures are frozen: personal bests are tied to them
  // (see __fixtures__/legacy-structures.json).
  { id: 'w-tempest', slug: 'tempest', name: 'TEMPEST', symbol: '⛈', focus: 'full_body', difficulty: 'advanced', estimatedMinutesMin: 12, estimatedMinutesMax: 18, equipment: ['bodyweight'], format: 'fixed_rounds', identityColor: '#4ECDC4', progressionTier: 'standard', description: 'Five rounds of squats, push-ups and burpees where the burpees always land on legs that are already cooked.', structure: rounds(5, [{ exerciseId: 'air-squat', reps: 20 }, { exerciseId: 'push-up', reps: 15 }, { exerciseId: 'burpee', reps: 10 }]) },
  { id: 'w-ember', slug: 'ember', name: 'EMBER', symbol: '🔥', focus: 'core', difficulty: 'intermediate', estimatedMinutesMin: 10, estimatedMinutesMax: 14, equipment: ['mat'], format: 'fixed_rounds', identityColor: '#F4A261', progressionTier: 'foundation', description: 'Lunges and sit-ups light the fuse; the plank at the end of every round never gets shorter, however fast you move.', structure: rounds(4, [{ exerciseId: 'walking-lunge', reps: 12 }, { exerciseId: 'sit-up', reps: 12 }, { exerciseId: 'plank-hold', durationSec: 30 }]) },
  { id: 'w-riptide', slug: 'riptide', name: 'RIPTIDE', symbol: '🌊', focus: 'cardio', difficulty: 'intermediate', estimatedMinutesMin: 14, estimatedMinutesMax: 20, equipment: ['bodyweight'], format: 'chipper', identityColor: '#5B8DEF', progressionTier: 'standard', description: 'A descending chipper from 50 jacks to 10 burpees: easy to enter, hard to escape once the push-ups pull you under.', structure: { format: 'chipper', rounds: [{ roundNumber: 1, steps: [{ exerciseId: 'jumping-jack', reps: 50 }, { exerciseId: 'air-squat', reps: 40 }, { exerciseId: 'mountain-climber', reps: 30 }, { exerciseId: 'push-up', reps: 20 }, { exerciseId: 'burpee', reps: 10 }] }] } },
  { id: 'w-avalanche', slug: 'avalanche', name: 'AVALANCHE', symbol: '🏔', focus: 'lower', difficulty: 'advanced', estimatedMinutesMin: 14, estimatedMinutesMax: 20, equipment: ['bodyweight'], format: 'fixed_rounds', identityColor: '#E8ECF4', progressionTier: 'advanced', description: 'Three hundred leg reps in five rounds, and the jump squats arrive just as your quads run out.', structure: rounds(5, [{ exerciseId: 'air-squat', reps: 25 }, { exerciseId: 'walking-lunge', reps: 20 }, { exerciseId: 'jump-squat', reps: 15 }]) },
  { id: 'w-summit', slug: 'summit', name: 'SUMMIT', symbol: '△', focus: 'full_body', difficulty: 'elite', estimatedMinutesMin: 15, estimatedMinutesMax: 25, equipment: ['bodyweight'], format: 'ladder', identityColor: '#C9B1FF', progressionTier: 'elite', description: 'A ten-rung burpee ladder with 10 squats on every rung; the top three rungs are where the race is decided.', structure: { format: 'ladder', rounds: Array.from({ length: 10 }, (_, i) => ({ roundNumber: i + 1, steps: [{ exerciseId: 'burpee', reps: i + 1 }, { exerciseId: 'air-squat', reps: 10 }] })) } },
  { id: 'w-drift', slug: 'drift', name: 'DRIFT', symbol: '〰', focus: 'cardio', difficulty: 'beginner', estimatedMinutesMin: 8, estimatedMinutesMax: 12, equipment: ['bodyweight'], format: 'intervals', identityColor: '#7DD3FC', progressionTier: 'foundation', description: 'Eight 45-second bursts of easy cardio that teach you to pace before you learn to race.', structure: { format: 'intervals', intervalWorkSec: 45, intervalRestSec: 15, intervalRounds: 8, rounds: [{ roundNumber: 1, steps: [{ exerciseId: 'high-knees', durationSec: 45 }, { exerciseId: 'jumping-jack', durationSec: 45 }, { exerciseId: 'butt-kicks', durationSec: 45 }, { exerciseId: 'mountain-climber', durationSec: 45 }] }] } },
  { id: 'w-flare', slug: 'flare', name: 'FLARE', symbol: '☀', focus: 'upper', difficulty: 'intermediate', estimatedMinutesMin: 12, estimatedMinutesMax: 16, equipment: ['bench'], format: 'fixed_rounds', identityColor: '#FFD166', progressionTier: 'standard', description: 'Pike push-ups, dips and shoulder taps until your shoulders and triceps burn all the way through round four.', structure: rounds(4, [{ exerciseId: 'pike-push-up', reps: 15 }, { exerciseId: 'tricep-dip', reps: 20 }, { exerciseId: 'shoulder-tap', reps: 24 }]) },
  { id: 'w-cascade', slug: 'cascade', name: 'CASCADE', symbol: '▽', focus: 'lower', difficulty: 'intermediate', estimatedMinutesMin: 6, estimatedMinutesMax: 10, equipment: ['bodyweight'], format: 'chipper', identityColor: '#6BCB77', progressionTier: 'standard', description: 'A single-leg chipper that falls from 30 deadlifts to 6 jump squats: balance first, power last.', structure: { format: 'chipper', rounds: [{ roundNumber: 1, steps: [{ exerciseId: 'single-leg-deadlift', reps: 30 }, { exerciseId: 'reverse-lunge', reps: 24 }, { exerciseId: 'air-squat', reps: 18 }, { exerciseId: 'calf-raise', reps: 12 }, { exerciseId: 'jump-squat', reps: 6 }] }] } },
  { id: 'w-gale', slug: 'gale', name: 'GALE', symbol: '💨', focus: 'conditioning', difficulty: 'advanced', estimatedMinutesMin: 18, estimatedMinutesMax: 25, equipment: ['bodyweight'], format: 'amrap', identityColor: '#94A3B8', progressionTier: 'advanced', description: 'Twenty minutes of burpees, squats and jacks; your score is how long you refuse to slow down.', structure: { format: 'amrap', timeCapSec: 1200, rounds: [{ roundNumber: 1, steps: [{ exerciseId: 'burpee', reps: 5 }, { exerciseId: 'air-squat', reps: 10 }, { exerciseId: 'jumping-jack', reps: 15 }] }] } },
  { id: 'w-frost', slug: 'frost', name: 'FROST', symbol: '❄', focus: 'core', difficulty: 'intermediate', estimatedMinutesMin: 10, estimatedMinutesMax: 14, equipment: ['mat'], format: 'fixed_rounds', identityColor: '#BAE6FD', progressionTier: 'foundation', description: 'Five rounds of plank, bicycles and leg raises with no hiding place for a soft midline.', structure: rounds(5, [{ exerciseId: 'plank-hold', durationSec: 45 }, { exerciseId: 'bicycle-crunch', reps: 20 }, { exerciseId: 'leg-raise', reps: 15 }]) },
  { id: 'w-ridge', slug: 'ridge', name: 'RIDGE', symbol: '⛰', focus: 'full_body', difficulty: 'beginner', estimatedMinutesMin: 8, estimatedMinutesMax: 12, equipment: ['mat'], format: 'fixed_rounds', identityColor: '#A3E635', progressionTier: 'foundation', description: 'Three short rounds of squats, knee push-ups and half burpees: your first opponent, and your first rematch.', structure: rounds(3, [{ exerciseId: 'air-squat', reps: 15 }, { exerciseId: 'knee-push-up', reps: 10 }, { exerciseId: 'half-burpee', reps: 8 }]) },
  { id: 'w-surge', slug: 'surge', name: 'SURGE', symbol: '⚡', focus: 'cardio', difficulty: 'advanced', estimatedMinutesMin: 10, estimatedMinutesMax: 15, equipment: ['bodyweight'], format: 'intervals', identityColor: '#FDE047', progressionTier: 'advanced', description: 'Ten 40-second sprints of burpees, skaters and climbers with only 20 seconds to recover between them.', structure: { format: 'intervals', intervalWorkSec: 40, intervalRestSec: 20, intervalRounds: 10, rounds: [{ roundNumber: 1, steps: [{ exerciseId: 'burpee', durationSec: 40 }, { exerciseId: 'skater-hop', durationSec: 40 }, { exerciseId: 'mountain-climber', durationSec: 40 }] }] } },
  { id: 'w-horizon', slug: 'horizon', name: 'HORIZON', symbol: '◐', focus: 'mixed', difficulty: 'intermediate', estimatedMinutesMin: 14, estimatedMinutesMax: 20, equipment: ['bodyweight'], format: 'fixed_rounds', identityColor: '#FB7185', progressionTier: 'standard', description: 'Inchworms, push-ups, lunges and sprawls in four long rounds that test every link in the chain.', structure: rounds(4, [{ exerciseId: 'inchworm', reps: 8 }, { exerciseId: 'push-up', reps: 12 }, { exerciseId: 'walking-lunge', reps: 16 }, { exerciseId: 'sprawl', reps: 10 }]) },
  { id: 'w-quake', slug: 'quake', name: 'QUAKE', symbol: '◎', focus: 'lower', difficulty: 'elite', estimatedMinutesMin: 16, estimatedMinutesMax: 22, equipment: ['bodyweight'], format: 'fixed_rounds', identityColor: '#F97316', progressionTier: 'elite', description: 'Six rounds of nothing but jumping: 264 landings that punish tired legs and sloppy knees.', structure: rounds(6, [{ exerciseId: 'jump-squat', reps: 20 }, { exerciseId: 'jumping-lunge', reps: 16 }, { exerciseId: 'broad-jump', reps: 8 }]) },
  { id: 'w-mirage', slug: 'mirage', name: 'MIRAGE', symbol: '◈', focus: 'core', difficulty: 'beginner', estimatedMinutesMin: 6, estimatedMinutesMax: 10, equipment: ['mat'], format: 'fixed_rounds', identityColor: '#C4B5FD', progressionTier: 'foundation', description: 'Dead bugs, bird dogs and bridges: slow, controlled, and harder to do well than it looks.', structure: rounds(3, [{ exerciseId: 'dead-bug', reps: 10 }, { exerciseId: 'bird-dog', reps: 10 }, { exerciseId: 'glute-bridge', reps: 15 }]) },
  { id: 'w-vortex', slug: 'vortex', name: 'VORTEX', symbol: '🌀', focus: 'conditioning', difficulty: 'intermediate', estimatedMinutesMin: 12, estimatedMinutesMax: 16, equipment: ['bodyweight'], format: 'fixed_rounds', identityColor: '#38BDF8', progressionTier: 'standard', description: 'Squat thrusts and push-ups chased by 30 seconds of high knees, five times, with no rest built in.', structure: rounds(5, [{ exerciseId: 'squat-thrust', reps: 12 }, { exerciseId: 'push-up', reps: 10 }, { exerciseId: 'high-knees', durationSec: 30 }]) },
  { id: 'w-eclipse', slug: 'eclipse', name: 'ECLIPSE', symbol: '◉', focus: 'upper', difficulty: 'advanced', estimatedMinutesMin: 12, estimatedMinutesMax: 18, equipment: ['bodyweight'], format: 'fixed_rounds', identityColor: '#6366F1', progressionTier: 'advanced', description: '210 push-ups across three variations; when the diamonds go, so does your pace.', structure: rounds(5, [{ exerciseId: 'push-up', reps: 20 }, { exerciseId: 'diamond-push-up', reps: 10 }, { exerciseId: 'pike-push-up', reps: 12 }]) },
  { id: 'w-dune', slug: 'dune', name: 'DUNE', symbol: '⌒', focus: 'lower', difficulty: 'beginner', estimatedMinutesMin: 8, estimatedMinutesMax: 12, equipment: ['bodyweight'], format: 'fixed_rounds', identityColor: '#EAB308', progressionTier: 'foundation', description: 'Squats, reverse lunges and a 30-second wall sit: gentle on the joints, relentless on the quads.', structure: rounds(4, [{ exerciseId: 'air-squat', reps: 20 }, { exerciseId: 'reverse-lunge', reps: 12 }, { exerciseId: 'wall-sit', durationSec: 30 }]) },
  { id: 'w-current', slug: 'current', name: 'CURRENT', symbol: '⟿', focus: 'cardio', difficulty: 'intermediate', estimatedMinutesMin: 10, estimatedMinutesMax: 14, equipment: ['jump-rope'], format: 'intervals', identityColor: '#22D3EE', progressionTier: 'standard', description: 'Eight 50-second rounds alternating rope and jacks with only 10 seconds to breathe.', structure: { format: 'intervals', intervalWorkSec: 50, intervalRestSec: 10, intervalRounds: 8, rounds: [{ roundNumber: 1, steps: [{ exerciseId: 'jump-rope', durationSec: 50 }, { exerciseId: 'jumping-jack', durationSec: 50 }] }] } },
  { id: 'w-apex', slug: 'apex', name: 'APEX', symbol: '▲', focus: 'full_body', difficulty: 'elite', estimatedMinutesMin: 10, estimatedMinutesMax: 16, equipment: ['bodyweight'], format: 'chipper', identityColor: '#EF4444', progressionTier: 'elite', description: '160 reps, four movements, one pass, and the 40 burpees up front set the tone for everything after.', structure: { format: 'chipper', rounds: [{ roundNumber: 1, steps: [{ exerciseId: 'burpee', reps: 40 }, { exerciseId: 'push-up', reps: 40 }, { exerciseId: 'air-squat', reps: 40 }, { exerciseId: 'walking-lunge', reps: 40 }] }] } },
  { id: 'w-zenith', slug: 'zenith', name: 'ZENITH', symbol: '✦', focus: 'mixed', difficulty: 'advanced', estimatedMinutesMin: 15, estimatedMinutesMax: 22, equipment: ['bench'], format: 'fixed_rounds', identityColor: '#A78BFA', progressionTier: 'advanced', description: 'Step-ups, dips and bear crawls for five rounds: legs, then arms, then everything at once.', structure: rounds(5, [{ exerciseId: 'step-up', reps: 16 }, { exerciseId: 'tricep-dip', reps: 15 }, { exerciseId: 'bear-crawl', durationSec: 30 }]) },
  { id: 'w-rust', slug: 'rust', name: 'RUST', symbol: '⊛', focus: 'strength_endurance', difficulty: 'intermediate', estimatedMinutesMin: 12, estimatedMinutesMax: 16, equipment: ['mat'], format: 'fixed_rounds', identityColor: '#B45309', progressionTier: 'standard', description: 'Squat holds and planks bookend 15 push-ups every round; staying still is the hard part.', structure: rounds(4, [{ exerciseId: 'squat-hold', durationSec: 45 }, { exerciseId: 'push-up', reps: 15 }, { exerciseId: 'plank-hold', durationSec: 45 }]) },
  { id: 'w-nova', slug: 'nova', name: 'NOVA', symbol: '✹', focus: 'explosive', difficulty: 'advanced', estimatedMinutesMin: 10, estimatedMinutesMax: 14, equipment: ['bodyweight'], format: 'fixed_rounds', identityColor: '#F472B6', progressionTier: 'advanced', description: 'Jump squats, broad jumps and burpees in four explosive rounds; power fades fast, and so does your lead.', structure: rounds(4, [{ exerciseId: 'jump-squat', reps: 15 }, { exerciseId: 'broad-jump', reps: 6 }, { exerciseId: 'burpee', reps: 8 }]) },
  { id: 'w-shoal', slug: 'shoal', name: 'SHOAL', symbol: '≋', focus: 'low_impact', difficulty: 'beginner', estimatedMinutesMin: 8, estimatedMinutesMax: 12, equipment: ['mat'], format: 'fixed_rounds', identityColor: '#2DD4BF', progressionTier: 'foundation', description: 'Wall push-ups, bridges and bird dogs: a low-impact first race you win on control alone.', structure: rounds(3, [{ exerciseId: 'wall-push-up', reps: 12 }, { exerciseId: 'glute-bridge', reps: 15 }, { exerciseId: 'bird-dog', reps: 10 }]) },
  { id: 'w-cinder', slug: 'cinder', name: 'CINDER', symbol: '▪', focus: 'core', difficulty: 'advanced', estimatedMinutesMin: 12, estimatedMinutesMax: 16, equipment: ['mat'], format: 'fixed_rounds', identityColor: '#78716C', progressionTier: 'advanced', description: 'Hollow holds, V-ups and Russian twists for five rounds; your abs quit long before your lungs do.', structure: rounds(5, [{ exerciseId: 'hollow-hold', durationSec: 30 }, { exerciseId: 'v-up', reps: 12 }, { exerciseId: 'russian-twist', reps: 20 }]) },
  { id: 'w-stratus', slug: 'stratus', name: 'STRATUS', symbol: '☁', focus: 'mixed', difficulty: 'intermediate', estimatedMinutesMin: 14, estimatedMinutesMax: 18, equipment: ['bodyweight'], format: 'fixed_rounds', identityColor: '#CBD5E1', progressionTier: 'standard', description: 'Plank jacks, squats and shoulder taps in four rounds that keep you bouncing between floor and feet.', structure: rounds(4, [{ exerciseId: 'plank-jack', reps: 20 }, { exerciseId: 'air-squat', reps: 20 }, { exerciseId: 'shoulder-tap', reps: 20 }]) },
  { id: 'w-bastion', slug: 'bastion', name: 'BASTION', symbol: '⬡', focus: 'strength_endurance', difficulty: 'elite', estimatedMinutesMin: 18, estimatedMinutesMax: 25, equipment: ['bench'], format: 'fixed_rounds', identityColor: '#64748B', progressionTier: 'elite', description: 'Six rounds of decline push-ups, Cossack squats and plank-to-push-ups: strength endurance with nowhere to hide.', structure: rounds(6, [{ exerciseId: 'decline-push-up', reps: 12 }, { exerciseId: 'cossack-squat', reps: 12 }, { exerciseId: 'plank-to-push-up', reps: 16 }]) },
  { id: 'w-pulse', slug: 'pulse', name: 'PULSE', symbol: '♥', focus: 'cardio', difficulty: 'beginner', estimatedMinutesMin: 5, estimatedMinutesMax: 8, equipment: ['bodyweight'], format: 'intervals', identityColor: '#FB923C', progressionTier: 'foundation', description: 'Six 30-second rounds of high knees: the shortest race in the library, and the best place to start one.', structure: { format: 'intervals', intervalWorkSec: 30, intervalRestSec: 15, intervalRounds: 6, rounds: [{ roundNumber: 1, steps: [{ exerciseId: 'high-knees', durationSec: 30 }] }] } },
  { id: 'w-onyx', slug: 'onyx', name: 'ONYX', symbol: '◼', focus: 'full_body', difficulty: 'intermediate', estimatedMinutesMin: 12, estimatedMinutesMax: 18, equipment: ['bodyweight'], format: 'fixed_rounds', identityColor: '#1E293B', progressionTier: 'standard', description: 'Crab walks, push-ups and lunges for four rounds; the crab walk taxes your shoulders right before every push-up set.', structure: rounds(4, [{ exerciseId: 'crab-walk', durationSec: 30 }, { exerciseId: 'push-up', reps: 12 }, { exerciseId: 'walking-lunge', reps: 12 }]) },
  { id: 'w-aurora', slug: 'aurora', name: 'AURORA', symbol: '⌇', focus: 'mixed', difficulty: 'intermediate', estimatedMinutesMin: 16, estimatedMinutesMax: 22, equipment: ['mat'], format: 'fixed_rounds', identityColor: '#86EFAC', progressionTier: 'standard', description: 'Single-leg deadlifts, push-ups and side planks across five rounds that reward balance over speed.', structure: rounds(5, [{ exerciseId: 'single-leg-deadlift', reps: 10 }, { exerciseId: 'push-up', reps: 10 }, { exerciseId: 'side-plank', durationSec: 30 }]) },
  { id: 'w-reef', slug: 'reef', name: 'REEF', symbol: '❋', focus: 'low_impact', difficulty: 'beginner', estimatedMinutesMin: 10, estimatedMinutesMax: 14, equipment: ['mat'], format: 'fixed_rounds', identityColor: '#14B8A6', progressionTier: 'foundation', description: 'Box breathing, dead bugs and reverse lunges: a calm, low-impact race against your own control.', structure: rounds(4, [{ exerciseId: 'box-breather', durationSec: 30 }, { exerciseId: 'dead-bug', reps: 12 }, { exerciseId: 'reverse-lunge', reps: 10 }]) },

  // ---------------------------------------------------------------------------
  // EMOM benchmarks
  // ---------------------------------------------------------------------------
  {
    id: 'w-squall',
    slug: 'squall',
    name: 'SQUALL',
    symbol: '◬',
    focus: 'full_body',
    difficulty: 'beginner',
    estimatedMinutesMin: 10,
    estimatedMinutesMax: 11,
    equipment: ['bodyweight'],
    format: 'emom',
    identityColor: '#60A5FA',
    progressionTier: 'foundation',
    description: 'Eight squats and four half burpees at the top of every minute; move fast and the rest of the minute is yours.',
    structure: emom(10, [[rep('air-squat', 8), rep('half-burpee', 4)]]),
  },
  {
    id: 'w-monsoon',
    slug: 'monsoon',
    name: 'MONSOON',
    symbol: '⁂',
    focus: 'conditioning',
    difficulty: 'intermediate',
    estimatedMinutesMin: 12,
    estimatedMinutesMax: 13,
    equipment: ['kettlebell'],
    format: 'emom',
    identityColor: '#3B82F6',
    progressionTier: 'standard',
    description: 'Twelve minutes alternating kettlebell swings and burpees; every second you save is rest you get to keep.',
    structure: emom(12, [[rep('kettlebell-swing', 12)], [rep('burpee', 7)]]),
  },
  {
    id: 'w-granite',
    slug: 'granite',
    name: 'GRANITE',
    symbol: '⬢',
    focus: 'strength_endurance',
    difficulty: 'intermediate',
    estimatedMinutesMin: 16,
    estimatedMinutesMax: 17,
    equipment: ['pull-up-bar'],
    format: 'emom',
    identityColor: '#9CA3AF',
    progressionTier: 'standard',
    description: 'Pull-ups, push-ups, knee raises and lunges on a four-minute cycle, four times through, with no shortcuts.',
    structure: emom(16, [[rep('pull-up', 3)], [rep('push-up', 10)], [rep('hanging-knee-raise', 8)], [rep('reverse-lunge', 14)]]),
  },
  {
    id: 'w-meteor',
    slug: 'meteor',
    name: 'METEOR',
    symbol: '✶',
    focus: 'full_body',
    difficulty: 'advanced',
    estimatedMinutesMin: 10,
    estimatedMinutesMax: 11,
    equipment: ['dumbbells'],
    format: 'emom',
    identityColor: '#F43F5E',
    progressionTier: 'advanced',
    description: 'Thrusters and devil presses on alternating minutes; by minute seven the rest you were banking is gone.',
    structure: emom(10, [[rep('dumbbell-thruster', 8)], [rep('devil-press', 5)]]),
  },

  // ---------------------------------------------------------------------------
  // AMRAP benchmarks
  // ---------------------------------------------------------------------------
  {
    id: 'w-lagoon',
    slug: 'lagoon',
    name: 'LAGOON',
    symbol: '◡',
    focus: 'full_body',
    difficulty: 'beginner',
    estimatedMinutesMin: 10,
    estimatedMinutesMax: 11,
    equipment: ['mat'],
    format: 'amrap',
    identityColor: '#34D399',
    progressionTier: 'foundation',
    description: 'Ten calm-looking minutes of squats, knee push-ups and sit-ups that get deeper every round.',
    structure: amrap(10, [rep('air-squat', 10), rep('knee-push-up', 8), rep('sit-up', 8)]),
  },
  {
    id: 'w-cyclone',
    slug: 'cyclone',
    name: 'CYCLONE',
    symbol: '⊚',
    focus: 'conditioning',
    difficulty: 'intermediate',
    estimatedMinutesMin: 12,
    estimatedMinutesMax: 13,
    equipment: ['kettlebell'],
    format: 'amrap',
    identityColor: '#8B5CF6',
    progressionTier: 'standard',
    description: 'Twelve minutes spinning through swings, push-ups and lunges: hips, chest, legs, and straight back to the bell.',
    structure: amrap(12, [rep('kettlebell-swing', 15), rep('push-up', 10), rep('walking-lunge', 12)]),
  },
  {
    id: 'w-kiln',
    slug: 'kiln',
    name: 'KILN',
    symbol: '⌂',
    focus: 'strength_endurance',
    difficulty: 'intermediate',
    estimatedMinutesMin: 18,
    estimatedMinutesMax: 19,
    equipment: ['dumbbells'],
    format: 'amrap',
    identityColor: '#D97706',
    progressionTier: 'standard',
    description: 'Eighteen minutes where the dumbbells barely leave your hands: deadlift, row, press, lunge, repeat.',
    structure: amrap(18, [rep('dumbbell-deadlift', 10), rep('dumbbell-row', 10), rep('dumbbell-press', 8), rep('dumbbell-lunge', 12)]),
  },
  {
    id: 'w-torrent',
    slug: 'torrent',
    name: 'TORRENT',
    symbol: '◢',
    focus: 'mixed',
    difficulty: 'advanced',
    estimatedMinutesMin: 14,
    estimatedMinutesMax: 15,
    equipment: ['pull-up-bar'],
    format: 'amrap',
    identityColor: '#0EA5E9',
    progressionTier: 'advanced',
    description: 'Fourteen minutes of pull-ups, knee raises and jump squats; your grip decides how long you keep up.',
    structure: amrap(14, [rep('pull-up', 3), rep('hanging-knee-raise', 6), rep('jump-squat', 9)]),
  },

  // ---------------------------------------------------------------------------
  // Interval benchmarks
  // ---------------------------------------------------------------------------
  {
    id: 'w-scorch',
    slug: 'scorch',
    name: 'SCORCH',
    symbol: '✷',
    focus: 'cardio',
    difficulty: 'advanced',
    estimatedMinutesMin: 4,
    estimatedMinutesMax: 5,
    equipment: ['bodyweight'],
    format: 'intervals',
    identityColor: '#DC2626',
    progressionTier: 'advanced',
    description: 'Eight 20-second all-out bursts of burpees and jump squats with 10 seconds between: four minutes that feel like forty.',
    structure: intervals(20, 10, 8, ['burpee', 'jump-squat']),
  },
  {
    id: 'w-undertow',
    slug: 'undertow',
    name: 'UNDERTOW',
    symbol: '◒',
    focus: 'upper',
    difficulty: 'intermediate',
    estimatedMinutesMin: 8,
    estimatedMinutesMax: 9,
    equipment: ['band'],
    format: 'intervals',
    identityColor: '#1D4ED8',
    progressionTier: 'standard',
    description: 'Eight 40-second rounds trading pushes for band pulls; the pull-aparts look easy until your upper back drags you under.',
    structure: intervals(40, 20, 8, ['band-pull-apart', 'push-up', 'band-pull-apart', 'pike-push-up']),
  },
  {
    id: 'w-spindrift',
    slug: 'spindrift',
    name: 'SPINDRIFT',
    symbol: '❖',
    focus: 'cardio',
    difficulty: 'intermediate',
    estimatedMinutesMin: 9,
    estimatedMinutesMax: 10,
    equipment: ['jump-rope'],
    format: 'intervals',
    identityColor: '#7FD8F5',
    progressionTier: 'standard',
    description: 'Twelve 30-second rounds where the rope keeps coming back; every trip costs reps you will not get back.',
    structure: intervals(30, 15, 12, ['jump-rope', 'mountain-climber', 'jump-rope', 'squat-thrust']),
  },
  {
    id: 'w-trench',
    slug: 'trench',
    name: 'TRENCH',
    symbol: '▿',
    focus: 'core',
    difficulty: 'intermediate',
    estimatedMinutesMin: 11,
    estimatedMinutesMax: 13,
    equipment: ['mat'],
    format: 'intervals',
    identityColor: '#0F766E',
    progressionTier: 'standard',
    description: 'Twelve 40-second core rounds of hollow rocks, bicycles, flutter kicks and twists until your midline gives out.',
    structure: intervals(40, 20, 12, ['hollow-rock', 'bicycle-crunch', 'flutter-kick', 'russian-twist']),
  },
  {
    id: 'w-forge',
    slug: 'forge',
    name: 'FORGE',
    symbol: '⬟',
    focus: 'strength_endurance',
    difficulty: 'advanced',
    estimatedMinutesMin: 10,
    estimatedMinutesMax: 11,
    equipment: ['dumbbells'],
    format: 'intervals',
    identityColor: '#EA580C',
    progressionTier: 'advanced',
    description: 'Ten 40-second rounds hammering snatches, squats, rows, presses and burpees; every rep you bank is score.',
    structure: intervals(40, 20, 10, ['dumbbell-snatch', 'goblet-squat', 'dumbbell-row', 'dumbbell-press', 'burpee']),
  },
  {
    id: 'w-inferno',
    slug: 'inferno',
    name: 'INFERNO',
    symbol: '✺',
    focus: 'conditioning',
    difficulty: 'elite',
    estimatedMinutesMin: 10,
    estimatedMinutesMax: 12,
    equipment: ['bodyweight'],
    format: 'intervals',
    identityColor: '#B91C1C',
    progressionTier: 'elite',
    description: 'Sixteen 30-second rounds of burpees, tuck jumps, climbers and jumping lunges with 10 seconds between; it never cools down.',
    structure: intervals(30, 10, 16, ['burpee', 'tuck-jump', 'mountain-climber', 'jumping-lunge']),
  },

  // ---------------------------------------------------------------------------
  // For-time benchmarks
  // ---------------------------------------------------------------------------
  {
    id: 'w-zephyr',
    slug: 'zephyr',
    name: 'ZEPHYR',
    symbol: '◠',
    focus: 'low_impact',
    difficulty: 'beginner',
    estimatedMinutesMin: 9,
    estimatedMinutesMax: 12,
    equipment: ['mat'],
    format: 'fixed_rounds',
    identityColor: '#A5F3FC',
    progressionTier: 'foundation',
    description: 'A steady four-rounder that moves you sideways, up and down; no jumping, just clean reps against the clock.',
    structure: rounds(4, [rep('lateral-lunge', 10), rep('wall-push-up', 10), rep('glute-bridge', 12), rep('bird-dog', 8)], 30),
  },
  {
    id: 'w-pebble',
    slug: 'pebble',
    name: 'PEBBLE',
    symbol: '◍',
    focus: 'strength_endurance',
    difficulty: 'beginner',
    estimatedMinutesMin: 8,
    estimatedMinutesMax: 11,
    equipment: ['dumbbells'],
    format: 'fixed_rounds',
    identityColor: '#D6D3D1',
    progressionTier: 'foundation',
    description: 'Three rounds of the four dumbbell basics with a full minute between: learn the pattern, then race it.',
    structure: rounds(3, [rep('goblet-squat', 10), rep('dumbbell-floor-press', 10), rep('dumbbell-row', 10), rep('dumbbell-deadlift', 10)], 60),
  },
  {
    id: 'w-overhang',
    slug: 'overhang',
    name: 'OVERHANG',
    symbol: '⟁',
    focus: 'upper',
    difficulty: 'beginner',
    estimatedMinutesMin: 7,
    estimatedMinutesMax: 10,
    equipment: ['pull-up-bar', 'mat'],
    format: 'fixed_rounds',
    identityColor: '#A8A29E',
    progressionTier: 'foundation',
    description: 'Hangs, slow negatives and hollow holds: the groundwork for your first pull-up, timed so you can watch it arrive.',
    structure: rounds(4, [hold('dead-hang', 30), rep('negative-pull-up', 3), hold('hollow-hold', 20)], 60),
  },
  {
    id: 'w-basalt',
    slug: 'basalt',
    name: 'BASALT',
    symbol: '⬣',
    focus: 'strength_endurance',
    difficulty: 'intermediate',
    estimatedMinutesMin: 12,
    estimatedMinutesMax: 16,
    equipment: ['dumbbells'],
    format: 'fixed_rounds',
    identityColor: '#475569',
    progressionTier: 'standard',
    description: 'Five rounds of squat, row and press with a fixed minute to reset, so every second of work shows on the clock.',
    structure: rounds(5, [rep('goblet-squat', 12), rep('dumbbell-row', 10), rep('dumbbell-press', 8)], 60),
  },
  {
    id: 'w-crag',
    slug: 'crag',
    name: 'CRAG',
    symbol: '◮',
    focus: 'upper',
    difficulty: 'intermediate',
    estimatedMinutesMin: 9,
    estimatedMinutesMax: 13,
    equipment: ['pull-up-bar'],
    format: 'fixed_rounds',
    identityColor: '#84CC16',
    progressionTier: 'standard',
    description: 'Five rounds of chin-ups, knee raises and squats where your grip, not your lungs, sets the pace.',
    structure: rounds(5, [rep('chin-up', 4), rep('hanging-knee-raise', 8), rep('air-squat', 16)], 30),
  },
  {
    id: 'w-mesa',
    slug: 'mesa',
    name: 'MESA',
    symbol: '▰',
    focus: 'lower',
    difficulty: 'intermediate',
    estimatedMinutesMin: 12,
    estimatedMinutesMax: 16,
    equipment: ['bench'],
    format: 'fixed_rounds',
    identityColor: '#C2410C',
    progressionTier: 'standard',
    description: 'One bench, four rounds: the split squats make every hip thrust heavier and every dip meaner.',
    structure: rounds(4, [rep('bulgarian-split-squat', 16), rep('hip-thrust', 15), rep('tricep-dip', 12)], 60),
  },
  {
    id: 'w-thunder',
    slug: 'thunder',
    name: 'THUNDER',
    symbol: '⌁',
    focus: 'explosive',
    difficulty: 'advanced',
    estimatedMinutesMin: 12,
    estimatedMinutesMax: 16,
    equipment: ['bodyweight'],
    format: 'fixed_rounds',
    identityColor: '#FACC15',
    progressionTier: 'advanced',
    description: 'Star jumps, tuck jumps, archer push-ups and skaters for five rounds: every rep loud, every landing quiet.',
    structure: rounds(5, [rep('star-jump', 10), rep('tuck-jump', 6), rep('archer-push-up', 10), rep('skater-hop', 16)], 30),
  },
  {
    id: 'w-obsidian',
    slug: 'obsidian',
    name: 'OBSIDIAN',
    symbol: '◆',
    focus: 'strength_endurance',
    difficulty: 'advanced',
    estimatedMinutesMin: 14,
    estimatedMinutesMax: 20,
    equipment: ['kettlebell'],
    format: 'fixed_rounds',
    identityColor: '#6D28D9',
    progressionTier: 'advanced',
    description: 'Six rounds of swings, pistols and archer push-ups: sharp, unforgiving, and built on single-limb strength.',
    structure: rounds(6, [rep('kettlebell-swing', 15), rep('pistol-squat', 8), rep('archer-push-up', 10)], 45),
  },

  // ---------------------------------------------------------------------------
  // Chippers
  // ---------------------------------------------------------------------------
  {
    id: 'w-sandbar',
    slug: 'sandbar',
    name: 'SANDBAR',
    symbol: '▱',
    focus: 'full_body',
    difficulty: 'beginner',
    estimatedMinutesMin: 8,
    estimatedMinutesMax: 12,
    equipment: ['mat'],
    format: 'chipper',
    identityColor: '#FCD34D',
    progressionTier: 'foundation',
    description: 'A beginner chipper that steps down from 50 to 10; the countdown keeps you moving when your legs say stop.',
    structure: chipper([rep('jumping-jack', 50), rep('air-squat', 40), rep('glute-bridge', 30), rep('reverse-lunge', 20), rep('knee-push-up', 10)]),
  },
  {
    id: 'w-ledge',
    slug: 'ledge',
    name: 'LEDGE',
    symbol: '◩',
    focus: 'mixed',
    difficulty: 'intermediate',
    estimatedMinutesMin: 9,
    estimatedMinutesMax: 13,
    equipment: ['bench'],
    format: 'chipper',
    identityColor: '#65A30D',
    progressionTier: 'standard',
    description: 'A 50-40-30-20-10 bench chipper that starts in your legs and finishes in your arms.',
    structure: chipper([rep('step-up', 50), rep('hip-thrust', 40), rep('tricep-dip', 30), rep('bulgarian-split-squat', 20), rep('decline-push-up', 10)]),
  },
  {
    id: 'w-magma',
    slug: 'magma',
    name: 'MAGMA',
    symbol: '⊗',
    focus: 'full_body',
    difficulty: 'elite',
    estimatedMinutesMin: 12,
    estimatedMinutesMax: 18,
    equipment: ['dumbbells'],
    format: 'chipper',
    identityColor: '#FF5722',
    progressionTier: 'elite',
    description: 'One pass of snatches, squats, devil presses, renegade rows and lunges: 160 reps that move slower than they read.',
    structure: chipper([rep('dumbbell-snatch', 40), rep('goblet-squat', 30), rep('devil-press', 20), rep('renegade-row', 30), rep('dumbbell-lunge', 40)]),
  },

  // ---------------------------------------------------------------------------
  // Ladders
  // ---------------------------------------------------------------------------
  {
    id: 'w-quarry',
    slug: 'quarry',
    name: 'QUARRY',
    symbol: '⬠',
    focus: 'conditioning',
    difficulty: 'intermediate',
    estimatedMinutesMin: 8,
    estimatedMinutesMax: 12,
    equipment: ['kettlebell'],
    format: 'ladder',
    identityColor: '#A16207',
    progressionTier: 'standard',
    description: 'Swings fall from 20 to 2 while push-ups climb from 1 to 10; the middle rungs are where the race turns.',
    structure: ladder(10, (n) => [rep('kettlebell-swing', 22 - 2 * n), rep('push-up', n)]),
  },
  {
    id: 'w-pinnacle',
    slug: 'pinnacle',
    name: 'PINNACLE',
    symbol: '◭',
    focus: 'full_body',
    difficulty: 'elite',
    estimatedMinutesMin: 18,
    estimatedMinutesMax: 26,
    equipment: ['pull-up-bar'],
    format: 'ladder',
    identityColor: '#E879F9',
    progressionTier: 'elite',
    description: 'Ten rungs climbing to 10 pull-ups, 20 push-ups and 30 squats: 330 reps, and the top three rungs are the race.',
    structure: ladder(10, (n) => [rep('pull-up', n), rep('push-up', 2 * n), rep('air-squat', 3 * n)]),
  },

  // ---------------------------------------------------------------------------
  // Warm-ups (not raced)
  // ---------------------------------------------------------------------------
  {
    id: 'w-daybreak',
    slug: 'daybreak',
    name: 'DAYBREAK',
    symbol: '◓',
    focus: 'mobility',
    difficulty: 'beginner',
    estimatedMinutesMin: 5,
    estimatedMinutesMax: 7,
    equipment: ['mat'],
    format: 'intervals',
    identityColor: '#FDBA74',
    progressionTier: 'foundation',
    kind: 'warmup',
    description: 'Six minutes from shoulders to hips that gets every joint ready before any race.',
    structure: intervals(40, 5, 8, ['arm-circles', 'leg-swings', 'cat-cow', 'worlds-greatest-stretch', 'inchworm', 'open-book', 'hip-flexor-stretch', 'jumping-jack']),
  },
  {
    id: 'w-thaw',
    slug: 'thaw',
    name: 'THAW',
    symbol: '◇',
    focus: 'mobility',
    difficulty: 'beginner',
    estimatedMinutesMin: 4,
    estimatedMinutesMax: 6,
    equipment: ['mat'],
    format: 'fixed_rounds',
    identityColor: '#93C5FD',
    progressionTier: 'foundation',
    kind: 'warmup',
    description: 'Two quick passes of leg swings, hip openers and lateral lunges to unlock the lower body before leg day.',
    structure: rounds(2, [hold('leg-swings', 30), hold('hip-flexor-stretch', 30), hold('worlds-greatest-stretch', 30), hold('lateral-lunge', 30)]),
  },
  {
    id: 'w-spark',
    slug: 'spark',
    name: 'SPARK',
    symbol: '✧',
    focus: 'mobility',
    difficulty: 'beginner',
    estimatedMinutesMin: 4,
    estimatedMinutesMax: 6,
    equipment: ['mat'],
    format: 'intervals',
    identityColor: '#FDE68A',
    progressionTier: 'foundation',
    kind: 'warmup',
    description: 'Arm circles, rotations and spinal waves that prime the shoulders for pushing and pulling.',
    structure: intervals(30, 5, 8, ['arm-circles', 'open-book', 'cat-cow', 'downward-dog']),
  },
  {
    id: 'w-kindling',
    slug: 'kindling',
    name: 'KINDLING',
    symbol: '⟐',
    focus: 'mobility',
    difficulty: 'beginner',
    estimatedMinutesMin: 6,
    estimatedMinutesMax: 8,
    equipment: ['bodyweight'],
    format: 'intervals',
    identityColor: '#FCA5A5',
    progressionTier: 'foundation',
    kind: 'warmup',
    description: 'Mobility first, then a build into high knees and butt kicks that turns a cold start into race pace.',
    structure: intervals(30, 10, 10, ['leg-swings', 'arm-circles', 'worlds-greatest-stretch', 'high-knees', 'inchworm', 'butt-kicks']),
  },

  // ---------------------------------------------------------------------------
  // Cool-downs (not raced)
  // ---------------------------------------------------------------------------
  {
    id: 'w-dusk',
    slug: 'dusk',
    name: 'DUSK',
    symbol: '◑',
    focus: 'mobility',
    difficulty: 'beginner',
    estimatedMinutesMin: 6,
    estimatedMinutesMax: 8,
    equipment: ['mat'],
    format: 'intervals',
    identityColor: '#818CF8',
    progressionTier: 'foundation',
    kind: 'cooldown',
    description: 'Eight slow holds from hips to spine, ending on the breath; the race is over, so let your heart rate follow.',
    structure: intervals(45, 5, 8, ['child-pose', 'cobra-stretch', 'downward-dog', 'hip-flexor-stretch', 'open-book', 'cat-cow', 'worlds-greatest-stretch', 'box-breather']),
  },
  {
    id: 'w-ebb',
    slug: 'ebb',
    name: 'EBB',
    symbol: '◖',
    focus: 'mobility',
    difficulty: 'beginner',
    estimatedMinutesMin: 5,
    estimatedMinutesMax: 7,
    equipment: ['mat'],
    format: 'fixed_rounds',
    identityColor: '#5EEAD4',
    progressionTier: 'foundation',
    kind: 'cooldown',
    description: 'Long holds for the hips, hamstrings and back after a leg-heavy race, finished with a minute of box breathing.',
    structure: rounds(1, [
      hold('hip-flexor-stretch', 60),
      hold('worlds-greatest-stretch', 60),
      hold('downward-dog', 45),
      hold('child-pose', 60),
      hold('cobra-stretch', 45),
      hold('box-breather', 60),
    ]),
  },
  {
    id: 'w-lull',
    slug: 'lull',
    name: 'LULL',
    symbol: '○',
    focus: 'mobility',
    difficulty: 'beginner',
    estimatedMinutesMin: 7,
    estimatedMinutesMax: 9,
    equipment: ['mat'],
    format: 'intervals',
    identityColor: '#C7D2FE',
    progressionTier: 'foundation',
    kind: 'cooldown',
    description: "Upper-back rotations, child's pose and slow breathing to bring your shoulders and your pulse back down.",
    structure: intervals(40, 5, 10, ['open-book', 'child-pose', 'cobra-stretch', 'cat-cow', 'box-breather']),
  },
];
